// Code generated by protocol/generate-artifacts.mjs. DO NOT EDIT.

package contract

const (
	OperatorV1Digest = "sha256:ab10778e2838f660157b000e442a1b97c5217fd92e66107122451b6894f0b9d3"
	AgentV1Digest    = "sha256:bdc7fc2230ea7db9ede54305f2adcb3e3c21451056e58f9467fd5dbcc4a3ddc7"
)
