// Code generated by protocol/generate-artifacts.mjs. DO NOT EDIT.

package contract

const (
	OperatorV1Digest = "sha256:8d3d17b02ba67cedf20143971abecede4601210a6b6380d117f9f473e01b1e5e"
	AgentV1Digest    = "sha256:bdc7fc2230ea7db9ede54305f2adcb3e3c21451056e58f9467fd5dbcc4a3ddc7"
)
