package policypreset

import (
	"bytes"
	"encoding/json"
	"slices"
	"strings"
	"testing"

	"github.com/osolmaz/brokerkit/brokers/huggingface/internal/opcatalog"
	"github.com/osolmaz/brokerkit/brokers/huggingface/internal/policy"
)

func TestRenderRequestAllAgentOperations(t *testing.T) {
	artifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	if artifacts.Manifest.OperationCounts != (OperationCounts{Total: 258, Allow: 93, Request: 160, Deny: 5}) {
		t.Fatalf("operation counts = %+v", artifacts.Manifest.OperationCounts)
	}
	if _, err := policy.Parse(artifacts.PolicyJSON); err != nil {
		t.Fatalf("rendered policy is invalid: %v", err)
	}
	assertRuleEffect(t, artifacts.PolicyJSON, "repo.contents.read", "allow")
	assertRuleEffect(t, artifacts.PolicyJSON, "repo.create", "request")
	assertRuleEffect(t, artifacts.PolicyJSON, "repo.delete", "request")
	assertRuleEffect(t, artifacts.PolicyJSON, "service_account.token.create", "deny")
	assertRuleEffect(t, artifacts.PolicyJSON, "sandbox.port.proxy", "deny")
}

func TestRenderIsDeterministicAndNormalizesInputs(t *testing.T) {
	first, err := Render(NewProfile([]string{"worker", "agent"}, []string{"repo.delete", "repo.create"}))
	if err != nil {
		t.Fatal(err)
	}
	second, err := Render(NewProfile([]string{"agent", "worker"}, []string{"repo.create", "repo.delete"}))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.ProfileJSON, second.ProfileJSON) || !bytes.Equal(first.PolicyJSON, second.PolicyJSON) || !bytes.Equal(first.ManifestJSON, second.ManifestJSON) {
		t.Fatal("equivalent profiles produced different artifacts")
	}
	if first.Manifest.OperationCounts.Request != 158 || first.Manifest.OperationCounts.Deny != 7 {
		t.Fatalf("override counts = %+v", first.Manifest.OperationCounts)
	}
	assertRuleEffect(t, first.PolicyJSON, "repo.create", "deny")
}

func TestProfileRejectsInvalidAndAmbiguousInputs(t *testing.T) {
	tests := []Profile{
		{},
		{Version: 2, Preset: RequestAllAgentOperations, Clients: []string{"agent"}},
		{Version: 1, Preset: "unknown", Clients: []string{"agent"}},
		NewProfile(nil, nil),
		NewProfile([]string{"agent", "agent"}, nil),
		NewProfile([]string{" agent"}, nil),
		NewProfile([]string{"agent"}, []string{"repo.unknown"}),
		NewProfile([]string{"agent"}, []string{"repo.delete", "repo.delete"}),
	}
	for _, profile := range tests {
		if _, err := Render(profile); err == nil {
			t.Fatalf("Render(%+v) accepted invalid profile", profile)
		}
	}
	if _, err := ParseProfile([]byte(`{"version":1,"preset":"request-all-agent-operations","clients":["agent"],"denied_operations":[],"extra":true}`)); err == nil {
		t.Fatal("ParseProfile accepted unknown field")
	}
}

func TestCatalogNeverDefaultsDangerousOperationsToAllow(t *testing.T) {
	for _, descriptor := range opcatalog.MustAll() {
		if descriptor.DefaultPolicyEffect != opcatalog.DefaultEffectAllow {
			continue
		}
		if descriptor.Risk == opcatalog.RiskHigh || descriptor.Risk == opcatalog.RiskCritical || descriptor.AuthorizationMode == opcatalog.ModeExecution || descriptor.ExplicitOnly || descriptor.Sealed || descriptor.Internal || descriptor.CredentialOutputKind != nil || !descriptor.AgentFacing {
			t.Fatalf("dangerous operation defaults to allow: %+v", descriptor)
		}
	}
}

func TestCheckReportsCurrentModifiedAndInvalidArtifacts(t *testing.T) {
	artifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	current := Check(artifacts.ProfileJSON, artifacts.ManifestJSON, artifacts.PolicyJSON)
	if current.Status != DriftCurrent {
		t.Fatalf("current report = %+v", current)
	}
	modifiedPolicy := append([]byte(nil), artifacts.PolicyJSON...)
	modifiedPolicy = bytes.Replace(modifiedPolicy, []byte("Generated by"), []byte("Rendered by"), 1)
	modified := Check(artifacts.ProfileJSON, artifacts.ManifestJSON, modifiedPolicy)
	if modified.Status != DriftModified || !strings.Contains(strings.Join(modified.Details, " "), "policy digest") {
		t.Fatalf("modified report = %+v", modified)
	}
	invalid := Check([]byte("{}"), artifacts.ManifestJSON, artifacts.PolicyJSON)
	if invalid.Status != DriftInvalid {
		t.Fatalf("invalid report = %+v", invalid)
	}
}

func TestCheckRequiresPolicyToMatchRenderedProfile(t *testing.T) {
	agentArtifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	workerArtifacts, err := Render(NewProfile([]string{"worker"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	manifest := agentArtifacts.Manifest
	manifest.ProfileDigest = digest(workerArtifacts.ProfileJSON)
	manifestJSON, err := marshalCanonical(manifest)
	if err != nil {
		t.Fatal(err)
	}
	report := Check(workerArtifacts.ProfileJSON, manifestJSON, agentArtifacts.PolicyJSON)
	if report.Status != DriftModified || !strings.Contains(strings.Join(report.Details, " "), "deterministic render") {
		t.Fatalf("profile-policy mismatch report = %+v", report)
	}
}

func TestCheckReportsCatalogAndManifestDrift(t *testing.T) {
	artifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	stale := artifacts.Manifest
	stale.CatalogDigest = "sha256:stale"
	staleJSON, _ := marshalCanonical(stale)
	if report := Check(artifacts.ProfileJSON, staleJSON, artifacts.PolicyJSON); report.Status != DriftStale {
		t.Fatalf("stale report = %+v", report)
	}
	modified := artifacts.Manifest
	modified.Operations[0].Effect = opcatalog.DefaultEffectRequest
	modifiedJSON, _ := marshalCanonical(modified)
	report := Check(artifacts.ProfileJSON, modifiedJSON, artifacts.PolicyJSON)
	if report.Status != DriftModified || len(report.ChangedOperations) != 1 {
		t.Fatalf("modified manifest report = %+v", report)
	}
}

func TestCheckReportsRemovedCatalogOperationBeforeCurrentPolicyValidation(t *testing.T) {
	artifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	var document policyDocument
	if err := json.Unmarshal(artifacts.PolicyJSON, &document); err != nil {
		t.Fatal(err)
	}
	const retiredOperation = "repo.retired"
	document.Rules = append(document.Rules, policyRule{
		ID: "preset-repo-retired", Effect: string(opcatalog.DefaultEffectRequest),
		Clients: []string{"agent"}, Operations: []string{retiredOperation},
		Targets:     []map[string]any{{"kind": "repo", "type": "*", "owner": "*", "name": "*"}},
		Description: "Generated by a previous operation catalog.",
	})
	oldPolicy, err := marshalCanonical(document)
	if err != nil {
		t.Fatal(err)
	}
	manifest := artifacts.Manifest
	retired := manifest.Operations[0]
	retired.Name = retiredOperation
	retired.Effect = opcatalog.DefaultEffectRequest
	manifest.Operations = append(manifest.Operations, retired)
	manifest.OperationCounts.Total++
	manifest.OperationCounts.Request++
	manifest.CatalogDigest = "sha256:previous-catalog"
	manifest.PolicyDigest = digest(oldPolicy)
	manifestJSON, err := marshalCanonical(manifest)
	if err != nil {
		t.Fatal(err)
	}
	report := Check(artifacts.ProfileJSON, manifestJSON, oldPolicy)
	if report.Status != DriftStale || !slices.Contains(report.RemovedOperations, retiredOperation) {
		t.Fatalf("removed-operation report = %+v", report)
	}
}

func TestParseManifestRejectsMalformedArtifacts(t *testing.T) {
	artifacts, err := Render(NewProfile([]string{"agent"}, nil))
	if err != nil {
		t.Fatal(err)
	}
	wrongVersion := artifacts.Manifest
	wrongVersion.Version = 2
	missingDigest := artifacts.Manifest
	missingDigest.PolicyDigest = ""
	wrongCount := artifacts.Manifest
	wrongCount.OperationCounts.Total--
	tests := [][]byte{[]byte("{"), append(append([]byte(nil), artifacts.ManifestJSON...), []byte("{}")...)}
	for _, manifest := range []Manifest{wrongVersion, missingDigest, wrongCount} {
		data, _ := marshalCanonical(manifest)
		tests = append(tests, data)
	}
	for _, data := range tests {
		if _, err := parseManifest(data); err == nil {
			t.Fatalf("parseManifest accepted %q", data)
		}
	}
}

func assertRuleEffect(t *testing.T, data []byte, operation, effect string) {
	t.Helper()
	var document struct {
		Rules []struct {
			Effect     string   `json:"effect"`
			Operations []string `json:"operations"`
		} `json:"rules"`
	}
	if err := json.Unmarshal(data, &document); err != nil {
		t.Fatal(err)
	}
	for _, rule := range document.Rules {
		if len(rule.Operations) == 1 && rule.Operations[0] == operation {
			if rule.Effect != effect {
				t.Fatalf("%s effect = %q, want %q", operation, rule.Effect, effect)
			}
			return
		}
	}
	t.Fatalf("operation %s missing from policy containing %s", operation, strings.TrimSpace(string(data)))
}
