// Package operatorwire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1-0.20260620164211-2ed9ad814b45 DO NOT EDIT.
package operatorwire

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

const (
	OperatorBearerScopes operatorBearerContextKey = "operatorBearer.Scopes"
)

// Defines values for Action.
const (
	Approve Action = "approve"
	Deny    Action = "deny"
	Revoke  Action = "revoke"
)

// Valid indicates whether the value is a known member of the Action enum.
func (e Action) Valid() bool {
	switch e {
	case Approve:
		return true
	case Deny:
		return true
	case Revoke:
		return true
	default:
		return false
	}
}

// Defines values for BrokerEventKind.
const (
	ExecutionAmbiguous BrokerEventKind = "execution.ambiguous"
	ExecutionFailed    BrokerEventKind = "execution.failed"
	ExecutionSucceeded BrokerEventKind = "execution.succeeded"
	GrantConsumed      BrokerEventKind = "grant.consumed"
	GrantReleased      BrokerEventKind = "grant.released"
	GrantReserved      BrokerEventKind = "grant.reserved"
	GrantRevoked       BrokerEventKind = "grant.revoked"
	RequestApproved    BrokerEventKind = "request.approved"
	RequestCanceled    BrokerEventKind = "request.canceled"
	RequestCreated     BrokerEventKind = "request.created"
	RequestDenied      BrokerEventKind = "request.denied"
	RequestExpired     BrokerEventKind = "request.expired"
)

// Valid indicates whether the value is a known member of the BrokerEventKind enum.
func (e BrokerEventKind) Valid() bool {
	switch e {
	case ExecutionAmbiguous:
		return true
	case ExecutionFailed:
		return true
	case ExecutionSucceeded:
		return true
	case GrantConsumed:
		return true
	case GrantReleased:
		return true
	case GrantReserved:
		return true
	case GrantRevoked:
		return true
	case RequestApproved:
		return true
	case RequestCanceled:
		return true
	case RequestCreated:
		return true
	case RequestDenied:
		return true
	case RequestExpired:
		return true
	default:
		return false
	}
}

// Defines values for DescriptorApiVersion.
const (
	BrokerkitIooperatorv1 DescriptorApiVersion = "brokerkit.io/operator/v1"
)

// Valid indicates whether the value is a known member of the DescriptorApiVersion enum.
func (e DescriptorApiVersion) Valid() bool {
	switch e {
	case BrokerkitIooperatorv1:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ConstraintExceeded     ErrorCode = "constraint_exceeded"
	CursorExpired          ErrorCode = "cursor_expired"
	Forbidden              ErrorCode = "forbidden"
	IdempotencyConflict    ErrorCode = "idempotency_conflict"
	InternalError          ErrorCode = "internal_error"
	InvalidDecisionToken   ErrorCode = "invalid_decision_token"
	InvalidRequest         ErrorCode = "invalid_request"
	InvalidTransition      ErrorCode = "invalid_transition"
	MethodNotAllowed       ErrorCode = "method_not_allowed"
	NotFound               ErrorCode = "not_found"
	RevisionConflict       ErrorCode = "revision_conflict"
	TemporarilyUnavailable ErrorCode = "temporarily_unavailable"
	Unauthorized           ErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ConstraintExceeded:
		return true
	case CursorExpired:
		return true
	case Forbidden:
		return true
	case IdempotencyConflict:
		return true
	case InternalError:
		return true
	case InvalidDecisionToken:
		return true
	case InvalidRequest:
		return true
	case InvalidTransition:
		return true
	case MethodNotAllowed:
		return true
	case NotFound:
		return true
	case RevisionConflict:
		return true
	case TemporarilyUnavailable:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for NotificationDecisionKind.
const (
	Telegram NotificationDecisionKind = "telegram"
)

// Valid indicates whether the value is a known member of the NotificationDecisionKind enum.
func (e NotificationDecisionKind) Valid() bool {
	switch e {
	case Telegram:
		return true
	default:
		return false
	}
}

// Defines values for PresentationRisk.
const (
	Critical PresentationRisk = "critical"
	High     PresentationRisk = "high"
	Low      PresentationRisk = "low"
	Medium   PresentationRisk = "medium"
	Unknown  PresentationRisk = "unknown"
)

// Valid indicates whether the value is a known member of the PresentationRisk enum.
func (e PresentationRisk) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for Status.
const (
	StatusActive   Status = "active"
	StatusCanceled Status = "canceled"
	StatusConsumed Status = "consumed"
	StatusDenied   Status = "denied"
	StatusExpired  Status = "expired"
	StatusPending  Status = "pending"
	StatusRevoked  Status = "revoked"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case StatusActive:
		return true
	case StatusCanceled:
		return true
	case StatusConsumed:
		return true
	case StatusDenied:
		return true
	case StatusExpired:
		return true
	case StatusPending:
		return true
	case StatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for StatusGroup.
const (
	StatusGroupActive  StatusGroup = "active"
	StatusGroupAll     StatusGroup = "all"
	StatusGroupHistory StatusGroup = "history"
	StatusGroupPending StatusGroup = "pending"
)

// Valid indicates whether the value is a known member of the StatusGroup enum.
func (e StatusGroup) Valid() bool {
	switch e {
	case StatusGroupActive:
		return true
	case StatusGroupAll:
		return true
	case StatusGroupHistory:
		return true
	case StatusGroupPending:
		return true
	default:
		return false
	}
}

// Defines values for UISnapshotApiVersion.
const (
	UISnapshotApiVersionBrokerkitIooperatorUiv1 UISnapshotApiVersion = "brokerkit.io/operator-ui/v1"
)

// Valid indicates whether the value is a known member of the UISnapshotApiVersion enum.
func (e UISnapshotApiVersion) Valid() bool {
	switch e {
	case UISnapshotApiVersionBrokerkitIooperatorUiv1:
		return true
	default:
		return false
	}
}

// Defines values for UISnapshotEventApiVersion.
const (
	UISnapshotEventApiVersionBrokerkitIooperatorUiv1 UISnapshotEventApiVersion = "brokerkit.io/operator-ui/v1"
)

// Valid indicates whether the value is a known member of the UISnapshotEventApiVersion enum.
func (e UISnapshotEventApiVersion) Valid() bool {
	switch e {
	case UISnapshotEventApiVersionBrokerkitIooperatorUiv1:
		return true
	default:
		return false
	}
}

// Defines values for UISummaryApiVersion.
const (
	UISummaryApiVersionBrokerkitIooperatorUiv1 UISummaryApiVersion = "brokerkit.io/operator-ui/v1"
)

// Valid indicates whether the value is a known member of the UISummaryApiVersion enum.
func (e UISummaryApiVersion) Valid() bool {
	switch e {
	case UISummaryApiVersionBrokerkitIooperatorUiv1:
		return true
	default:
		return false
	}
}

// Action defines model for Action.
type Action string

// ApprovalBounds defines model for ApprovalBounds.
type ApprovalBounds struct {
	MaxDurationSeconds int                    `json:"max_duration_seconds"`
	MaxUses            nullable.Nullable[int] `json:"max_uses"`
}

// BrokerEvent defines model for BrokerEvent.
type BrokerEvent struct {
	Cursor     string          `json:"cursor"`
	Kind       BrokerEventKind `json:"kind"`
	OccurredAt time.Time       `json:"occurred_at"`
	RequestId  string          `json:"request_id"`
	Revision   int             `json:"revision"`
	Status     Status          `json:"status"`
	UsedCount  int             `json:"used_count"`
}

// BrokerEventKind defines model for BrokerEvent.Kind.
type BrokerEventKind string

// BrokerRequest defines model for BrokerRequest.
type BrokerRequest struct {
	ActiveExpiresAt          *time.Time             `json:"active_expires_at,omitempty"`
	AllowedActions           []Action               `json:"allowed_actions"`
	ApprovalBounds           *ApprovalBounds        `json:"approval_bounds,omitempty"`
	DecidedAt                *time.Time             `json:"decided_at,omitempty"`
	DecidedBy                *string                `json:"decided_by,omitempty"`
	DecidedOnBehalfOf        *string                `json:"decided_on_behalf_of,omitempty"`
	GrantedMaxUses           nullable.Nullable[int] `json:"granted_max_uses"`
	Id                       string                 `json:"id"`
	Operation                string                 `json:"operation"`
	PendingExpiresAt         *time.Time             `json:"pending_expires_at,omitempty"`
	Presentation             Presentation           `json:"presentation"`
	PresentationUnavailable  *bool                  `json:"presentation_unavailable,omitempty"`
	RequestReason            *string                `json:"request_reason,omitempty"`
	RequestedAt              time.Time              `json:"requested_at"`
	RequestedDurationSeconds int                    `json:"requested_duration_seconds"`
	RequestedMaxUses         nullable.Nullable[int] `json:"requested_max_uses"`
	Requester                string                 `json:"requester"`
	Revision                 int                    `json:"revision"`
	Status                   Status                 `json:"status"`
	UsedCount                int                    `json:"used_count"`
}

// Constraints defines model for Constraints.
type Constraints struct {
	DurationSeconds *int                   `json:"duration_seconds,omitempty"`
	MaxUses         nullable.Nullable[int] `json:"max_uses,omitempty"`
}

// Decision defines model for Decision.
type Decision struct {
	Constraints      *Constraints          `json:"constraints,omitempty"`
	ExpectedRevision int                   `json:"expected_revision"`
	IdempotencyKey   string                `json:"idempotency_key"`
	Notification     *NotificationDecision `json:"notification,omitempty"`
	OnBehalfOf       *string               `json:"on_behalf_of,omitempty"`
}

// Descriptor defines model for Descriptor.
type Descriptor struct {
	ApiVersion     DescriptorApiVersion `json:"api_version"`
	BuildId        string               `json:"build_id"`
	ContractDigest string               `json:"contract_digest"`
}

// DescriptorApiVersion defines model for Descriptor.ApiVersion.
type DescriptorApiVersion string

// Error defines model for Error.
type Error struct {
	Code          ErrorCode      `json:"code"`
	CorrelationId string         `json:"correlation_id"`
	Current       *BrokerRequest `json:"current,omitempty"`
	Message       string         `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error Error `json:"error"`
}

// Fact defines model for Fact.
type Fact struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

// Health defines model for Health.
type Health struct {
	BuildId        string `json:"build_id"`
	ContractDigest string `json:"contract_digest"`
	Status         string `json:"status"`
}

// NotificationDecision defines model for NotificationDecision.
type NotificationDecision struct {
	ChatId             int                      `json:"chat_id"`
	DecisionToken      string                   `json:"decision_token"`
	Kind               NotificationDecisionKind `json:"kind"`
	MessageId          int                      `json:"message_id"`
	PresentationDigest string                   `json:"presentation_digest"`
	PresentationJson   string                   `json:"presentation_json"`
	RenderedDigest     string                   `json:"rendered_digest"`
	Renderer           string                   `json:"renderer"`
	Text               string                   `json:"text"`
}

// NotificationDecisionKind defines model for NotificationDecision.Kind.
type NotificationDecisionKind string

// Presentation defines model for Presentation.
type Presentation struct {
	Facts    *[]Fact          `json:"facts,omitempty"`
	PlanHash *string          `json:"plan_hash,omitempty"`
	Risk     PresentationRisk `json:"risk"`
	Summary  *string          `json:"summary,omitempty"`
	Target   string           `json:"target"`
	Title    string           `json:"title"`
	Warnings *[]Warning       `json:"warnings,omitempty"`
}

// PresentationRisk defines model for PresentationRisk.
type PresentationRisk string

// RequestPage defines model for RequestPage.
type RequestPage struct {
	EventCursor *string         `json:"event_cursor,omitempty"`
	NextCursor  *string         `json:"next_cursor,omitempty"`
	Requests    []BrokerRequest `json:"requests"`
}

// Status defines model for Status.
type Status string

// StatusGroup defines model for StatusGroup.
type StatusGroup string

// UIRequest defines model for UIRequest.
type UIRequest struct {
	Handle      string        `json:"handle"`
	Request     BrokerRequest `json:"request"`
	SourceId    string        `json:"source_id"`
	SourceLabel string        `json:"source_label"`
}

// UISnapshot defines model for UISnapshot.
type UISnapshot struct {
	ApiVersion       UISnapshotApiVersion `json:"api_version"`
	Cursor           string               `json:"cursor"`
	DeliveryFailures *int                 `json:"delivery_failures,omitempty"`
	Requests         []UIRequest          `json:"requests"`
	Sources          []UISourceHealth     `json:"sources"`
	SynchronizedAt   time.Time            `json:"synchronized_at"`
}

// UISnapshotApiVersion defines model for UISnapshot.ApiVersion.
type UISnapshotApiVersion string

// UISnapshotEvent defines model for UISnapshotEvent.
type UISnapshotEvent struct {
	ApiVersion UISnapshotEventApiVersion `json:"api_version"`
	Changed    bool                      `json:"changed"`
	Cursor     string                    `json:"cursor"`
}

// UISnapshotEventApiVersion defines model for UISnapshotEvent.ApiVersion.
type UISnapshotEventApiVersion string

// UISourceHealth defines model for UISourceHealth.
type UISourceHealth struct {
	Error      *string    `json:"error,omitempty"`
	Healthy    bool       `json:"healthy"`
	Id         string     `json:"id"`
	Label      string     `json:"label"`
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
}

// UISummary defines model for UISummary.
type UISummary struct {
	ApiVersion UISummaryApiVersion `json:"api_version"`
	Cursor     string              `json:"cursor"`
	Healthy    bool                `json:"healthy"`
	Pending    int                 `json:"pending"`
}

// UISummaryApiVersion defines model for UISummary.ApiVersion.
type UISummaryApiVersion string

// Warning defines model for Warning.
type Warning struct {
	Severity PresentationRisk `json:"severity"`
	Text     string           `json:"text"`
}

// RequestID defines model for RequestID.
type RequestID = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// operatorBearerContextKey is the context key for operatorBearer security scheme
type operatorBearerContextKey string

// StreamOperatorEventsParams defines parameters for StreamOperatorEvents.
type StreamOperatorEventsParams struct {
	Cursor      *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// ListOperatorRequestsParams defines parameters for ListOperatorRequests.
type ListOperatorRequestsParams struct {
	Status     *StatusGroup `form:"status,omitempty" json:"status,omitempty"`
	Requester  *string      `form:"requester,omitempty" json:"requester,omitempty"`
	Operation  *string      `form:"operation,omitempty" json:"operation,omitempty"`
	TargetKind *string      `form:"target_kind,omitempty" json:"target_kind,omitempty"`
	Cursor     *string      `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *int         `form:"limit,omitempty" json:"limit,omitempty"`
}

// DecideOperatorRequestJSONRequestBody defines body for DecideOperatorRequest for application/json ContentType.
type DecideOperatorRequestJSONRequestBody = Decision

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// DiscoverOperator performs a GET /.well-known/brokerkit-operator (the `DiscoverOperator` operationId) request.
	DiscoverOperator(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StreamOperatorEvents performs a GET /api/operator/v1/events (the `StreamOperatorEvents` operationId) request.
	StreamOperatorEvents(ctx context.Context, params *StreamOperatorEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListOperatorRequests performs a GET /api/operator/v1/requests (the `ListOperatorRequests` operationId) request.
	//
	// Target fields use additional bounded query names with the target. prefix.
	ListOperatorRequests(ctx context.Context, params *ListOperatorRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOperatorRequest performs a GET /api/operator/v1/requests/{id} (the `GetOperatorRequest` operationId) request.
	GetOperatorRequest(ctx context.Context, id RequestID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DecideOperatorRequestWithBody performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request,
	// with any type of body and a specified content type.
	DecideOperatorRequestWithBody(ctx context.Context, id RequestID, action Action, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DecideOperatorRequest performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request.
	// Takes a body of the `application/json` content type.
	DecideOperatorRequest(ctx context.Context, id RequestID, action Action, body DecideOperatorRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OperatorHealth performs a GET /healthz (the `OperatorHealth` operationId) request.
	OperatorHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OperatorReady performs a GET /readyz (the `OperatorReady` operationId) request.
	OperatorReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// DiscoverOperator performs a GET /.well-known/brokerkit-operator (the `DiscoverOperator` operationId) request.
func (c *Client) DiscoverOperator(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverOperatorRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// StreamOperatorEvents performs a GET /api/operator/v1/events (the `StreamOperatorEvents` operationId) request.
func (c *Client) StreamOperatorEvents(ctx context.Context, params *StreamOperatorEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStreamOperatorEventsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListOperatorRequests performs a GET /api/operator/v1/requests (the `ListOperatorRequests` operationId) request.
//
// Target fields use additional bounded query names with the target. prefix.
func (c *Client) ListOperatorRequests(ctx context.Context, params *ListOperatorRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListOperatorRequestsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetOperatorRequest performs a GET /api/operator/v1/requests/{id} (the `GetOperatorRequest` operationId) request.
func (c *Client) GetOperatorRequest(ctx context.Context, id RequestID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOperatorRequestRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DecideOperatorRequestWithBody performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request,
// with any type of body and a specified content type.
func (c *Client) DecideOperatorRequestWithBody(ctx context.Context, id RequestID, action Action, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDecideOperatorRequestRequestWithBody(c.Server, id, action, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DecideOperatorRequest performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) DecideOperatorRequest(ctx context.Context, id RequestID, action Action, body DecideOperatorRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDecideOperatorRequestRequest(c.Server, id, action, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OperatorHealth performs a GET /healthz (the `OperatorHealth` operationId) request.
func (c *Client) OperatorHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOperatorHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OperatorReady performs a GET /readyz (the `OperatorReady` operationId) request.
func (c *Client) OperatorReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOperatorReadyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDiscoverOperatorRequest constructs an http.Request for the DiscoverOperator method
func NewDiscoverOperatorRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/.well-known/brokerkit-operator")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStreamOperatorEventsRequest constructs an http.Request for the StreamOperatorEvents method
func NewStreamOperatorEventsRequest(server string, params *StreamOperatorEventsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/operator/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.LastEventID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Last-Event-ID", *params.LastEventID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Last-Event-ID", headerParam0)
		}

	}

	return req, nil
}

// NewListOperatorRequestsRequest constructs an http.Request for the ListOperatorRequests method
func NewListOperatorRequestsRequest(server string, params *ListOperatorRequestsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/operator/v1/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Requester != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "requester", *params.Requester, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Operation != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "operation", *params.Operation, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.TargetKind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "target_kind", *params.TargetKind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOperatorRequestRequest constructs an http.Request for the GetOperatorRequest method
func NewGetOperatorRequestRequest(server string, id RequestID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/operator/v1/requests/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDecideOperatorRequestRequest calls the generic DecideOperatorRequest builder with application/json body
func NewDecideOperatorRequestRequest(server string, id RequestID, action Action, body DecideOperatorRequestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDecideOperatorRequestRequestWithBody(server, id, action, "application/json", bodyReader)
}

// NewDecideOperatorRequestRequestWithBody constructs an http.Request for the DecideOperatorRequest method, with any body, and a specified content type
func NewDecideOperatorRequestRequestWithBody(server string, id RequestID, action Action, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "action", action, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/operator/v1/requests/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOperatorHealthRequest constructs an http.Request for the OperatorHealth method
func NewOperatorHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOperatorReadyRequest constructs an http.Request for the OperatorReady method
func NewOperatorReadyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// DiscoverOperatorWithResponse performs a GET /.well-known/brokerkit-operator (the `DiscoverOperator` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DiscoverOperatorWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DiscoverOperatorResponse, error)

	// StreamOperatorEventsWithResponse performs a GET /api/operator/v1/events (the `StreamOperatorEvents` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	StreamOperatorEventsWithResponse(ctx context.Context, params *StreamOperatorEventsParams, reqEditors ...RequestEditorFn) (*StreamOperatorEventsResponse, error)

	// ListOperatorRequestsWithResponse performs a GET /api/operator/v1/requests (the `ListOperatorRequests` operationId) request.
	//
	// Target fields use additional bounded query names with the target. prefix.
	//
	// Returns a wrapper object for the known response body format(s).
	ListOperatorRequestsWithResponse(ctx context.Context, params *ListOperatorRequestsParams, reqEditors ...RequestEditorFn) (*ListOperatorRequestsResponse, error)

	// GetOperatorRequestWithResponse performs a GET /api/operator/v1/requests/{id} (the `GetOperatorRequest` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetOperatorRequestWithResponse(ctx context.Context, id RequestID, reqEditors ...RequestEditorFn) (*GetOperatorRequestResponse, error)

	// DecideOperatorRequestWithBodyWithResponse performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	DecideOperatorRequestWithBodyWithResponse(ctx context.Context, id RequestID, action Action, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DecideOperatorRequestResponse, error)

	// DecideOperatorRequestWithResponse performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	DecideOperatorRequestWithResponse(ctx context.Context, id RequestID, action Action, body DecideOperatorRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*DecideOperatorRequestResponse, error)

	// OperatorHealthWithResponse performs a GET /healthz (the `OperatorHealth` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	OperatorHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OperatorHealthResponse, error)

	// OperatorReadyWithResponse performs a GET /readyz (the `OperatorReady` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	OperatorReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OperatorReadyResponse, error)
}

type DiscoverOperatorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Descriptor
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DiscoverOperatorResponse) GetJSON200() *Descriptor {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DiscoverOperatorResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DiscoverOperatorResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DiscoverOperatorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverOperatorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverOperatorResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StreamOperatorEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r StreamOperatorEventsResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r StreamOperatorEventsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r StreamOperatorEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StreamOperatorEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StreamOperatorEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListOperatorRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RequestPage
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListOperatorRequestsResponse) GetJSON200() *RequestPage {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListOperatorRequestsResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListOperatorRequestsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListOperatorRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListOperatorRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListOperatorRequestsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOperatorRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BrokerRequest
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetOperatorRequestResponse) GetJSON200() *BrokerRequest {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetOperatorRequestResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetOperatorRequestResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetOperatorRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOperatorRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOperatorRequestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DecideOperatorRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BrokerRequest
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DecideOperatorRequestResponse) GetJSON200() *BrokerRequest {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DecideOperatorRequestResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DecideOperatorRequestResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DecideOperatorRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DecideOperatorRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DecideOperatorRequestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type OperatorHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r OperatorHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r OperatorHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OperatorHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OperatorHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OperatorHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type OperatorReadyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r OperatorReadyResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r OperatorReadyResponse) GetJSON503() *ErrorResponse {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r OperatorReadyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OperatorReadyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OperatorReadyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OperatorReadyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DiscoverOperatorWithResponse performs a GET /.well-known/brokerkit-operator (the `DiscoverOperator` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DiscoverOperatorWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DiscoverOperatorResponse, error) {
	rsp, err := c.DiscoverOperator(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverOperatorResponse(rsp)
}

// StreamOperatorEventsWithResponse performs a GET /api/operator/v1/events (the `StreamOperatorEvents` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) StreamOperatorEventsWithResponse(ctx context.Context, params *StreamOperatorEventsParams, reqEditors ...RequestEditorFn) (*StreamOperatorEventsResponse, error) {
	rsp, err := c.StreamOperatorEvents(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStreamOperatorEventsResponse(rsp)
}

// ListOperatorRequestsWithResponse performs a GET /api/operator/v1/requests (the `ListOperatorRequests` operationId) request.
//
// Target fields use additional bounded query names with the target. prefix.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListOperatorRequestsWithResponse(ctx context.Context, params *ListOperatorRequestsParams, reqEditors ...RequestEditorFn) (*ListOperatorRequestsResponse, error) {
	rsp, err := c.ListOperatorRequests(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListOperatorRequestsResponse(rsp)
}

// GetOperatorRequestWithResponse performs a GET /api/operator/v1/requests/{id} (the `GetOperatorRequest` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetOperatorRequestWithResponse(ctx context.Context, id RequestID, reqEditors ...RequestEditorFn) (*GetOperatorRequestResponse, error) {
	rsp, err := c.GetOperatorRequest(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOperatorRequestResponse(rsp)
}

// DecideOperatorRequestWithBodyWithResponse performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DecideOperatorRequestWithBodyWithResponse(ctx context.Context, id RequestID, action Action, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DecideOperatorRequestResponse, error) {
	rsp, err := c.DecideOperatorRequestWithBody(ctx, id, action, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDecideOperatorRequestResponse(rsp)
}

// DecideOperatorRequestWithResponse performs a POST /api/operator/v1/requests/{id}/{action} (the `DecideOperatorRequest` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DecideOperatorRequestWithResponse(ctx context.Context, id RequestID, action Action, body DecideOperatorRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*DecideOperatorRequestResponse, error) {
	rsp, err := c.DecideOperatorRequest(ctx, id, action, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDecideOperatorRequestResponse(rsp)
}

// OperatorHealthWithResponse performs a GET /healthz (the `OperatorHealth` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) OperatorHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OperatorHealthResponse, error) {
	rsp, err := c.OperatorHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOperatorHealthResponse(rsp)
}

// OperatorReadyWithResponse performs a GET /readyz (the `OperatorReady` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) OperatorReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OperatorReadyResponse, error) {
	rsp, err := c.OperatorReady(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOperatorReadyResponse(rsp)
}

// ParseDiscoverOperatorResponse parses an HTTP response from a DiscoverOperatorWithResponse call
func ParseDiscoverOperatorResponse(rsp *http.Response) (*DiscoverOperatorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverOperatorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Descriptor
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStreamOperatorEventsResponse parses an HTTP response from a StreamOperatorEventsWithResponse call
func ParseStreamOperatorEventsResponse(rsp *http.Response) (*StreamOperatorEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StreamOperatorEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListOperatorRequestsResponse parses an HTTP response from a ListOperatorRequestsWithResponse call
func ParseListOperatorRequestsResponse(rsp *http.Response) (*ListOperatorRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListOperatorRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RequestPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetOperatorRequestResponse parses an HTTP response from a GetOperatorRequestWithResponse call
func ParseGetOperatorRequestResponse(rsp *http.Response) (*GetOperatorRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOperatorRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BrokerRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDecideOperatorRequestResponse parses an HTTP response from a DecideOperatorRequestWithResponse call
func ParseDecideOperatorRequestResponse(rsp *http.Response) (*DecideOperatorRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DecideOperatorRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BrokerRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseOperatorHealthResponse parses an HTTP response from a OperatorHealthWithResponse call
func ParseOperatorHealthResponse(rsp *http.Response) (*OperatorHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OperatorHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOperatorReadyResponse parses an HTTP response from a OperatorReadyWithResponse call
func ParseOperatorReadyResponse(rsp *http.Response) (*OperatorReadyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OperatorReadyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /.well-known/brokerkit-operator)
	DiscoverOperator(ctx echo.Context) error

	// (GET /api/operator/v1/events)
	StreamOperatorEvents(ctx echo.Context, params StreamOperatorEventsParams) error

	// (GET /api/operator/v1/requests)
	ListOperatorRequests(ctx echo.Context, params ListOperatorRequestsParams) error

	// (GET /api/operator/v1/requests/{id})
	GetOperatorRequest(ctx echo.Context, id RequestID) error

	// (POST /api/operator/v1/requests/{id}/{action})
	DecideOperatorRequest(ctx echo.Context, id RequestID, action Action) error

	// (GET /healthz)
	OperatorHealth(ctx echo.Context) error

	// (GET /readyz)
	OperatorReady(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DiscoverOperator converts echo context to params.
func (w *ServerInterfaceWrapper) DiscoverOperator(ctx echo.Context) error {
	var err error

	ctx.Set(string(OperatorBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DiscoverOperator(ctx)
	return err
}

// StreamOperatorEvents converts echo context to params.
func (w *ServerInterfaceWrapper) StreamOperatorEvents(ctx echo.Context) error {
	var err error

	ctx.Set(string(OperatorBearerScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamOperatorEventsParams
	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Last-Event-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Last-Event-ID")]; found {
		var LastEventID string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Last-Event-ID, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Last-Event-ID", valueList[0], &LastEventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Last-Event-ID: %s", err))
		}

		params.LastEventID = &LastEventID
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StreamOperatorEvents(ctx, params)
	return err
}

// ListOperatorRequests converts echo context to params.
func (w *ServerInterfaceWrapper) ListOperatorRequests(ctx echo.Context) error {
	var err error

	ctx.Set(string(OperatorBearerScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOperatorRequestsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "requester" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requester", ctx.QueryParams(), &params.Requester, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter requester: %s", err))
	}

	// ------------- Optional query parameter "operation" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "operation", ctx.QueryParams(), &params.Operation, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter operation: %s", err))
	}

	// ------------- Optional query parameter "target_kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_kind", ctx.QueryParams(), &params.TargetKind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter target_kind: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOperatorRequests(ctx, params)
	return err
}

// GetOperatorRequest converts echo context to params.
func (w *ServerInterfaceWrapper) GetOperatorRequest(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(OperatorBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOperatorRequest(ctx, id)
	return err
}

// DecideOperatorRequest converts echo context to params.
func (w *ServerInterfaceWrapper) DecideOperatorRequest(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(string(OperatorBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DecideOperatorRequest(ctx, id, action)
	return err
}

// OperatorHealth converts echo context to params.
func (w *ServerInterfaceWrapper) OperatorHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OperatorHealth(ctx)
	return err
}

// OperatorReady converts echo context to params.
func (w *ServerInterfaceWrapper) OperatorReady(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.OperatorReady(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/.well-known/brokerkit-operator", wrapper.DiscoverOperator, options.OperationMiddlewares["discoverOperator"]...)
	router.GET(options.BaseURL+"/api/operator/v1/events", wrapper.StreamOperatorEvents, options.OperationMiddlewares["streamOperatorEvents"]...)
	router.GET(options.BaseURL+"/api/operator/v1/requests", wrapper.ListOperatorRequests, options.OperationMiddlewares["listOperatorRequests"]...)
	router.GET(options.BaseURL+"/api/operator/v1/requests/:id", wrapper.GetOperatorRequest, options.OperationMiddlewares["getOperatorRequest"]...)
	router.POST(options.BaseURL+"/api/operator/v1/requests/:id/:action", wrapper.DecideOperatorRequest, options.OperationMiddlewares["decideOperatorRequest"]...)
	router.GET(options.BaseURL+"/healthz", wrapper.OperatorHealth, options.OperationMiddlewares["operatorHealth"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.OperatorReady, options.OperationMiddlewares["operatorReady"]...)

}
