// Package agentwire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1-0.20260620164211-2ed9ad814b45 DO NOT EDIT.
package agentwire

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	AgentBearerScopes agentBearerContextKey = "agentBearer.Scopes"
)

// Defines values for DescriptorApiVersion.
const (
	DescriptorApiVersionBrokerkitIoagentv1 DescriptorApiVersion = "brokerkit.io/agent/v1"
)

// Valid indicates whether the value is a known member of the DescriptorApiVersion enum.
func (e DescriptorApiVersion) Valid() bool {
	switch e {
	case DescriptorApiVersionBrokerkitIoagentv1:
		return true
	default:
		return false
	}
}

// Defines values for OperationApiVersion.
const (
	OperationApiVersionBrokerkitIoagentv1 OperationApiVersion = "brokerkit.io/agent/v1"
)

// Valid indicates whether the value is a known member of the OperationApiVersion enum.
func (e OperationApiVersion) Valid() bool {
	switch e {
	case OperationApiVersionBrokerkitIoagentv1:
		return true
	default:
		return false
	}
}

// Defines values for OperationPageApiVersion.
const (
	OperationPageApiVersionBrokerkitIoagentv1 OperationPageApiVersion = "brokerkit.io/agent/v1"
)

// Valid indicates whether the value is a known member of the OperationPageApiVersion enum.
func (e OperationPageApiVersion) Valid() bool {
	switch e {
	case OperationPageApiVersionBrokerkitIoagentv1:
		return true
	default:
		return false
	}
}

// Defines values for OperationSummaryApiVersion.
const (
	OperationSummaryApiVersionBrokerkitIoagentv1 OperationSummaryApiVersion = "brokerkit.io/agent/v1"
)

// Valid indicates whether the value is a known member of the OperationSummaryApiVersion enum.
func (e OperationSummaryApiVersion) Valid() bool {
	switch e {
	case OperationSummaryApiVersionBrokerkitIoagentv1:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	Approved  State = "approved"
	Canceled  State = "canceled"
	Denied    State = "denied"
	Executing State = "executing"
	Expired   State = "expired"
	Failed    State = "failed"
	Pending   State = "pending"
	Succeeded State = "succeeded"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case Approved:
		return true
	case Canceled:
		return true
	case Denied:
		return true
	case Executing:
		return true
	case Expired:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// CredentialDescriptor defines model for CredentialDescriptor.
type CredentialDescriptor struct {
	CredentialKind    string `json:"credential_kind"`
	Generation        int    `json:"generation"`
	Provider          string `json:"provider"`
	Ready             bool   `json:"ready"`
	VerificationState string `json:"verification_state"`
}

// Descriptor defines model for Descriptor.
type Descriptor struct {
	ApiVersion DescriptorApiVersion `json:"api_version"`
	Credential CredentialDescriptor `json:"credential"`
	Operations []string             `json:"operations"`
}

// DescriptorApiVersion defines model for Descriptor.ApiVersion.
type DescriptorApiVersion string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error OperationError `json:"error"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Operation defines model for Operation.
type Operation struct {
	ApiVersion     OperationApiVersion     `json:"api_version"`
	ApprovalId     *string                 `json:"approval_id,omitempty"`
	Arguments      map[string]interface{}  `json:"arguments"`
	Broker         string                  `json:"broker"`
	ClientId       string                  `json:"client_id"`
	CreatedAt      time.Time               `json:"created_at"`
	Error          *OperationError         `json:"error,omitempty"`
	Id             string                  `json:"id"`
	IdempotencyKey IdempotencyKey          `json:"idempotency_key"`
	Operation      string                  `json:"operation"`
	PlanDigest     *string                 `json:"plan_digest,omitempty"`
	Presentation   Presentation            `json:"presentation"`
	Reason         string                  `json:"reason"`
	Result         *map[string]interface{} `json:"result,omitempty"`
	Revision       int                     `json:"revision"`
	State          State                   `json:"state"`
	Target         map[string]interface{}  `json:"target"`
	TerminalAt     *time.Time              `json:"terminal_at,omitempty"`
	UpdatedAt      time.Time               `json:"updated_at"`
}

// OperationApiVersion defines model for Operation.ApiVersion.
type OperationApiVersion string

// OperationError defines model for OperationError.
type OperationError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// OperationPage defines model for OperationPage.
type OperationPage struct {
	ApiVersion OperationPageApiVersion `json:"api_version"`
	NextCursor *string                 `json:"next_cursor"`
	Operations []OperationSummary      `json:"operations"`
}

// OperationPageApiVersion defines model for OperationPage.ApiVersion.
type OperationPageApiVersion string

// OperationSummary defines model for OperationSummary.
type OperationSummary struct {
	ApiVersion     OperationSummaryApiVersion `json:"api_version"`
	Broker         string                     `json:"broker"`
	ClientId       string                     `json:"client_id"`
	CreatedAt      time.Time                  `json:"created_at"`
	Id             string                     `json:"id"`
	IdempotencyKey IdempotencyKey             `json:"idempotency_key"`
	Operation      string                     `json:"operation"`
	Presentation   Presentation               `json:"presentation"`
	Revision       int                        `json:"revision"`
	State          State                      `json:"state"`
	TerminalAt     *time.Time                 `json:"terminal_at,omitempty"`
	UpdatedAt      time.Time                  `json:"updated_at"`
}

// OperationSummaryApiVersion defines model for OperationSummary.ApiVersion.
type OperationSummaryApiVersion string

// Presentation defines model for Presentation.
type Presentation struct {
	Summary *string `json:"summary,omitempty"`
	Title   string  `json:"title"`
}

// State defines model for State.
type State string

// SubmitRequest defines model for SubmitRequest.
type SubmitRequest struct {
	Arguments      map[string]interface{} `json:"arguments"`
	IdempotencyKey IdempotencyKey         `json:"idempotency_key"`
	Operation      string                 `json:"operation"`
	Reason         string                 `json:"reason"`
	Target         map[string]interface{} `json:"target"`
}

// OperationID defines model for OperationID.
type OperationID = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = ErrorEnvelope

// agentBearerContextKey is the context key for agentBearer security scheme
type agentBearerContextKey string

// ListAgentOperationsParams defines parameters for ListAgentOperations.
type ListAgentOperationsParams struct {
	IdempotencyKey *IdempotencyKey `form:"idempotency_key,omitempty" json:"idempotency_key,omitempty"`
	State          *State          `form:"state,omitempty" json:"state,omitempty"`
	Limit          *int            `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor         *string         `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// WaitForAgentOperationParams defines parameters for WaitForAgentOperation.
type WaitForAgentOperationParams struct {
	AfterRevision *int `form:"after_revision,omitempty" json:"after_revision,omitempty"`
	WaitSeconds   *int `form:"wait_seconds,omitempty" json:"wait_seconds,omitempty"`
}

// SubmitAgentOperationJSONRequestBody defines body for SubmitAgentOperation for application/json ContentType.
type SubmitAgentOperationJSONRequestBody = SubmitRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// DiscoverAgent performs a GET /.well-known/brokerkit-agent (the `DiscoverAgent` operationId) request.
	DiscoverAgent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAgentOperations performs a GET /api/agent/v1/operations (the `ListAgentOperations` operationId) request.
	ListAgentOperations(ctx context.Context, params *ListAgentOperationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitAgentOperationWithBody performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request,
	// with any type of body and a specified content type.
	SubmitAgentOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitAgentOperation performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request.
	// Takes a body of the `application/json` content type.
	SubmitAgentOperation(ctx context.Context, body SubmitAgentOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAgentOperation performs a GET /api/agent/v1/operations/{id} (the `GetAgentOperation` operationId) request.
	GetAgentOperation(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelAgentOperation performs a POST /api/agent/v1/operations/{id}/cancel (the `CancelAgentOperation` operationId) request.
	CancelAgentOperation(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WaitForAgentOperation performs a GET /api/agent/v1/operations/{id}/events (the `WaitForAgentOperation` operationId) request.
	WaitForAgentOperation(ctx context.Context, id OperationID, params *WaitForAgentOperationParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// DiscoverAgent performs a GET /.well-known/brokerkit-agent (the `DiscoverAgent` operationId) request.
func (c *Client) DiscoverAgent(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverAgentRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListAgentOperations performs a GET /api/agent/v1/operations (the `ListAgentOperations` operationId) request.
func (c *Client) ListAgentOperations(ctx context.Context, params *ListAgentOperationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAgentOperationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitAgentOperationWithBody performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request,
// with any type of body and a specified content type.
func (c *Client) SubmitAgentOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitAgentOperationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitAgentOperation performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) SubmitAgentOperation(ctx context.Context, body SubmitAgentOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitAgentOperationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAgentOperation performs a GET /api/agent/v1/operations/{id} (the `GetAgentOperation` operationId) request.
func (c *Client) GetAgentOperation(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentOperationRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelAgentOperation performs a POST /api/agent/v1/operations/{id}/cancel (the `CancelAgentOperation` operationId) request.
func (c *Client) CancelAgentOperation(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelAgentOperationRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// WaitForAgentOperation performs a GET /api/agent/v1/operations/{id}/events (the `WaitForAgentOperation` operationId) request.
func (c *Client) WaitForAgentOperation(ctx context.Context, id OperationID, params *WaitForAgentOperationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWaitForAgentOperationRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDiscoverAgentRequest constructs an http.Request for the DiscoverAgent method
func NewDiscoverAgentRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/.well-known/brokerkit-agent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListAgentOperationsRequest constructs an http.Request for the ListAgentOperations method
func NewListAgentOperationsRequest(server string, params *ListAgentOperationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/v1/operations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.IdempotencyKey != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "idempotency_key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitAgentOperationRequest calls the generic SubmitAgentOperation builder with application/json body
func NewSubmitAgentOperationRequest(server string, body SubmitAgentOperationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitAgentOperationRequestWithBody(server, "application/json", bodyReader)
}

// NewSubmitAgentOperationRequestWithBody constructs an http.Request for the SubmitAgentOperation method, with any body, and a specified content type
func NewSubmitAgentOperationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/v1/operations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAgentOperationRequest constructs an http.Request for the GetAgentOperation method
func NewGetAgentOperationRequest(server string, id OperationID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/v1/operations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelAgentOperationRequest constructs an http.Request for the CancelAgentOperation method
func NewCancelAgentOperationRequest(server string, id OperationID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/v1/operations/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWaitForAgentOperationRequest constructs an http.Request for the WaitForAgentOperation method
func NewWaitForAgentOperationRequest(server string, id OperationID, params *WaitForAgentOperationParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/agent/v1/operations/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.AfterRevision != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "after_revision", *params.AfterRevision, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.WaitSeconds != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "wait_seconds", *params.WaitSeconds, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// DiscoverAgentWithResponse performs a GET /.well-known/brokerkit-agent (the `DiscoverAgent` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DiscoverAgentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DiscoverAgentResponse, error)

	// ListAgentOperationsWithResponse performs a GET /api/agent/v1/operations (the `ListAgentOperations` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListAgentOperationsWithResponse(ctx context.Context, params *ListAgentOperationsParams, reqEditors ...RequestEditorFn) (*ListAgentOperationsResponse, error)

	// SubmitAgentOperationWithBodyWithResponse performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	SubmitAgentOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitAgentOperationResponse, error)

	// SubmitAgentOperationWithResponse performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	SubmitAgentOperationWithResponse(ctx context.Context, body SubmitAgentOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitAgentOperationResponse, error)

	// GetAgentOperationWithResponse performs a GET /api/agent/v1/operations/{id} (the `GetAgentOperation` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetAgentOperationWithResponse(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*GetAgentOperationResponse, error)

	// CancelAgentOperationWithResponse performs a POST /api/agent/v1/operations/{id}/cancel (the `CancelAgentOperation` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CancelAgentOperationWithResponse(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*CancelAgentOperationResponse, error)

	// WaitForAgentOperationWithResponse performs a GET /api/agent/v1/operations/{id}/events (the `WaitForAgentOperation` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	WaitForAgentOperationWithResponse(ctx context.Context, id OperationID, params *WaitForAgentOperationParams, reqEditors ...RequestEditorFn) (*WaitForAgentOperationResponse, error)
}

type DiscoverAgentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Descriptor
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DiscoverAgentResponse) GetJSON200() *Descriptor {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DiscoverAgentResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DiscoverAgentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DiscoverAgentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverAgentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverAgentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListAgentOperationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *OperationPage
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListAgentOperationsResponse) GetJSON200() *OperationPage {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListAgentOperationsResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListAgentOperationsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListAgentOperationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAgentOperationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAgentOperationsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SubmitAgentOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Operation
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *Operation
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SubmitAgentOperationResponse) GetJSON200() *Operation {
	return r.JSON200
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r SubmitAgentOperationResponse) GetJSON202() *Operation {
	return r.JSON202
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r SubmitAgentOperationResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r SubmitAgentOperationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SubmitAgentOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitAgentOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubmitAgentOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAgentOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Operation
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAgentOperationResponse) GetJSON200() *Operation {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetAgentOperationResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetAgentOperationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAgentOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAgentOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelAgentOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Operation
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CancelAgentOperationResponse) GetJSON200() *Operation {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CancelAgentOperationResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CancelAgentOperationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelAgentOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelAgentOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelAgentOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type WaitForAgentOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Operation
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r WaitForAgentOperationResponse) GetJSON200() *Operation {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r WaitForAgentOperationResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r WaitForAgentOperationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r WaitForAgentOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WaitForAgentOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r WaitForAgentOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DiscoverAgentWithResponse performs a GET /.well-known/brokerkit-agent (the `DiscoverAgent` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DiscoverAgentWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DiscoverAgentResponse, error) {
	rsp, err := c.DiscoverAgent(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverAgentResponse(rsp)
}

// ListAgentOperationsWithResponse performs a GET /api/agent/v1/operations (the `ListAgentOperations` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListAgentOperationsWithResponse(ctx context.Context, params *ListAgentOperationsParams, reqEditors ...RequestEditorFn) (*ListAgentOperationsResponse, error) {
	rsp, err := c.ListAgentOperations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAgentOperationsResponse(rsp)
}

// SubmitAgentOperationWithBodyWithResponse performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) SubmitAgentOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitAgentOperationResponse, error) {
	rsp, err := c.SubmitAgentOperationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitAgentOperationResponse(rsp)
}

// SubmitAgentOperationWithResponse performs a POST /api/agent/v1/operations (the `SubmitAgentOperation` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) SubmitAgentOperationWithResponse(ctx context.Context, body SubmitAgentOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitAgentOperationResponse, error) {
	rsp, err := c.SubmitAgentOperation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitAgentOperationResponse(rsp)
}

// GetAgentOperationWithResponse performs a GET /api/agent/v1/operations/{id} (the `GetAgentOperation` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetAgentOperationWithResponse(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*GetAgentOperationResponse, error) {
	rsp, err := c.GetAgentOperation(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentOperationResponse(rsp)
}

// CancelAgentOperationWithResponse performs a POST /api/agent/v1/operations/{id}/cancel (the `CancelAgentOperation` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CancelAgentOperationWithResponse(ctx context.Context, id OperationID, reqEditors ...RequestEditorFn) (*CancelAgentOperationResponse, error) {
	rsp, err := c.CancelAgentOperation(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelAgentOperationResponse(rsp)
}

// WaitForAgentOperationWithResponse performs a GET /api/agent/v1/operations/{id}/events (the `WaitForAgentOperation` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) WaitForAgentOperationWithResponse(ctx context.Context, id OperationID, params *WaitForAgentOperationParams, reqEditors ...RequestEditorFn) (*WaitForAgentOperationResponse, error) {
	rsp, err := c.WaitForAgentOperation(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWaitForAgentOperationResponse(rsp)
}

// ParseDiscoverAgentResponse parses an HTTP response from a DiscoverAgentWithResponse call
func ParseDiscoverAgentResponse(rsp *http.Response) (*DiscoverAgentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverAgentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Descriptor
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListAgentOperationsResponse parses an HTTP response from a ListAgentOperationsWithResponse call
func ParseListAgentOperationsResponse(rsp *http.Response) (*ListAgentOperationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAgentOperationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OperationPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSubmitAgentOperationResponse parses an HTTP response from a SubmitAgentOperationWithResponse call
func ParseSubmitAgentOperationResponse(rsp *http.Response) (*SubmitAgentOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitAgentOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetAgentOperationResponse parses an HTTP response from a GetAgentOperationWithResponse call
func ParseGetAgentOperationResponse(rsp *http.Response) (*GetAgentOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCancelAgentOperationResponse parses an HTTP response from a CancelAgentOperationWithResponse call
func ParseCancelAgentOperationResponse(rsp *http.Response) (*CancelAgentOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelAgentOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseWaitForAgentOperationResponse parses an HTTP response from a WaitForAgentOperationWithResponse call
func ParseWaitForAgentOperationResponse(rsp *http.Response) (*WaitForAgentOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WaitForAgentOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Operation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /.well-known/brokerkit-agent)
	DiscoverAgent(ctx echo.Context) error

	// (GET /api/agent/v1/operations)
	ListAgentOperations(ctx echo.Context, params ListAgentOperationsParams) error

	// (POST /api/agent/v1/operations)
	SubmitAgentOperation(ctx echo.Context) error

	// (GET /api/agent/v1/operations/{id})
	GetAgentOperation(ctx echo.Context, id OperationID) error

	// (POST /api/agent/v1/operations/{id}/cancel)
	CancelAgentOperation(ctx echo.Context, id OperationID) error

	// (GET /api/agent/v1/operations/{id}/events)
	WaitForAgentOperation(ctx echo.Context, id OperationID, params WaitForAgentOperationParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DiscoverAgent converts echo context to params.
func (w *ServerInterfaceWrapper) DiscoverAgent(ctx echo.Context) error {
	var err error

	ctx.Set(string(AgentBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DiscoverAgent(ctx)
	return err
}

// ListAgentOperations converts echo context to params.
func (w *ServerInterfaceWrapper) ListAgentOperations(ctx echo.Context) error {
	var err error

	ctx.Set(string(AgentBearerScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentOperationsParams
	// ------------- Optional query parameter "idempotency_key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "idempotency_key", ctx.QueryParams(), &params.IdempotencyKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter idempotency_key: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", ctx.QueryParams(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAgentOperations(ctx, params)
	return err
}

// SubmitAgentOperation converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitAgentOperation(ctx echo.Context) error {
	var err error

	ctx.Set(string(AgentBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitAgentOperation(ctx)
	return err
}

// GetAgentOperation converts echo context to params.
func (w *ServerInterfaceWrapper) GetAgentOperation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(AgentBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAgentOperation(ctx, id)
	return err
}

// CancelAgentOperation converts echo context to params.
func (w *ServerInterfaceWrapper) CancelAgentOperation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(AgentBearerScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelAgentOperation(ctx, id)
	return err
}

// WaitForAgentOperation converts echo context to params.
func (w *ServerInterfaceWrapper) WaitForAgentOperation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(AgentBearerScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params WaitForAgentOperationParams
	// ------------- Optional query parameter "after_revision" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after_revision", ctx.QueryParams(), &params.AfterRevision, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter after_revision: %s", err))
	}

	// ------------- Optional query parameter "wait_seconds" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "wait_seconds", ctx.QueryParams(), &params.WaitSeconds, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter wait_seconds: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WaitForAgentOperation(ctx, id, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/.well-known/brokerkit-agent", wrapper.DiscoverAgent, options.OperationMiddlewares["discoverAgent"]...)
	router.GET(options.BaseURL+"/api/agent/v1/operations", wrapper.ListAgentOperations, options.OperationMiddlewares["listAgentOperations"]...)
	router.POST(options.BaseURL+"/api/agent/v1/operations", wrapper.SubmitAgentOperation, options.OperationMiddlewares["submitAgentOperation"]...)
	router.GET(options.BaseURL+"/api/agent/v1/operations/:id", wrapper.GetAgentOperation, options.OperationMiddlewares["getAgentOperation"]...)
	router.POST(options.BaseURL+"/api/agent/v1/operations/:id/cancel", wrapper.CancelAgentOperation, options.OperationMiddlewares["cancelAgentOperation"]...)
	router.GET(options.BaseURL+"/api/agent/v1/operations/:id/events", wrapper.WaitForAgentOperation, options.OperationMiddlewares["waitForAgentOperation"]...)

}
