// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type DecisionRecord struct {
	RequestID      string
	Action         string
	IdempotencyKey string
	RequestHash    string
	ResultRevision int64
	CreatedAt      string
}

type Grant struct {
	ID                    string
	DecisionTokenVerifier string
	Client                string
	ClientRequestID       string
	Operation             string
	TargetJson            string
	AttrsJson             string
	MetadataJson          string
	PlanDigest            sql.NullString
	Reason                string
	Status                string
	Revision              int64
	CreatedAt             string
	PendingExpiresAt      string
	ExpiresAt             sql.NullString
	DurationNs            int64
	RequestedDurationNs   int64
	PendingTimeoutNs      int64
	DecidedAt             sql.NullString
	DecidedBy             string
	DecidedOnBehalfOf     string
	DecisionReason        string
	UsedAt                sql.NullString
	UsedCount             int64
	UseRevision           int64
	ReservedCount         int64
	ReservedAt            sql.NullString
	ReservationRetained   int64
	ReservationRevision   int64
	MaxUses               int64
	RequestedMaxUses      int64
	ExpiredFrom           sql.NullString
}

type LifecycleEvent struct {
	Sequence    int64
	Cursor      string
	SubjectKind string
	SubjectID   string
	Kind        string
	Revision    int64
	OccurredAt  string
	PayloadJson string
}

type NotificationOutbox struct {
	ID             int64
	GrantID        string
	Kind           string
	PayloadJson    string
	IdempotencyKey string
	Status         string
	Attempts       int64
	AvailableAt    string
	ClaimedUntil   sql.NullString
	DeliveredAt    sql.NullString
	LastErrorCode  string
	CreatedAt      string
	UpdatedAt      string
}

type Operation struct {
	ID               string
	ApiVersion       string
	Broker           string
	ClientID         string
	IdempotencyKey   string
	Operation        string
	TargetJson       string
	ArgumentsJson    string
	Reason           string
	State            string
	Revision         int64
	CreatedAt        string
	UpdatedAt        string
	TerminalAt       sql.NullString
	ApprovalID       string
	PresentationJson string
	ResultJson       sql.NullString
	ErrorJson        sql.NullString
	PlanDigest       sql.NullString
}

type Plan struct {
	Digest     string
	SchemaName string
	Canonical  []byte
	CreatedAt  string
}
