// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsql

import (
	"context"
	"database/sql"
)

const countOperations = `-- name: CountOperations :one
SELECT count(*) FROM operations
`

// CountOperations
//
//	SELECT count(*) FROM operations
func (q *Queries) CountOperations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlans = `-- name: CountPlans :one
SELECT count(*) FROM plans
`

// CountPlans
//
//	SELECT count(*) FROM plans
func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGrantLifecycleEventsBefore = `-- name: DeleteGrantLifecycleEventsBefore :exec
DELETE FROM lifecycle_events WHERE subject_kind = 'grant' AND sequence < ?
`

// DeleteGrantLifecycleEventsBefore
//
//	DELETE FROM lifecycle_events WHERE subject_kind = 'grant' AND sequence < ?
func (q *Queries) DeleteGrantLifecycleEventsBefore(ctx context.Context, sequence int64) error {
	_, err := q.db.ExecContext(ctx, deleteGrantLifecycleEventsBefore, sequence)
	return err
}

const deleteTerminalOperationsBefore = `-- name: DeleteTerminalOperationsBefore :execrows
DELETE FROM operations
WHERE terminal_at IS NOT NULL AND terminal_at < ?
`

// DeleteTerminalOperationsBefore
//
//	DELETE FROM operations
//	WHERE terminal_at IS NOT NULL AND terminal_at < ?
func (q *Queries) DeleteTerminalOperationsBefore(ctx context.Context, terminalAt sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerminalOperationsBefore, terminalAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findOperationByIdempotency = `-- name: FindOperationByIdempotency :one
SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE client_id = ? AND idempotency_key = ?
`

type FindOperationByIdempotencyParams struct {
	ClientID       string
	IdempotencyKey string
}

// FindOperationByIdempotency
//
//	SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE client_id = ? AND idempotency_key = ?
func (q *Queries) FindOperationByIdempotency(ctx context.Context, arg FindOperationByIdempotencyParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, findOperationByIdempotency, arg.ClientID, arg.IdempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.Broker,
		&i.ClientID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.TargetJson,
		&i.ArgumentsJson,
		&i.Reason,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
		&i.ApprovalID,
		&i.PresentationJson,
		&i.ResultJson,
		&i.ErrorJson,
		&i.PlanDigest,
	)
	return i, err
}

const getOperationByID = `-- name: GetOperationByID :one
SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE id = ?
`

// GetOperationByID
//
//	SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE id = ?
func (q *Queries) GetOperationByID(ctx context.Context, id string) (Operation, error) {
	row := q.db.QueryRowContext(ctx, getOperationByID, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.Broker,
		&i.ClientID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.TargetJson,
		&i.ArgumentsJson,
		&i.Reason,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
		&i.ApprovalID,
		&i.PresentationJson,
		&i.ResultJson,
		&i.ErrorJson,
		&i.PlanDigest,
	)
	return i, err
}

const getOperationForClient = `-- name: GetOperationForClient :one
SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE id = ? AND client_id = ?
`

type GetOperationForClientParams struct {
	ID       string
	ClientID string
}

// GetOperationForClient
//
//	SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations WHERE id = ? AND client_id = ?
func (q *Queries) GetOperationForClient(ctx context.Context, arg GetOperationForClientParams) (Operation, error) {
	row := q.db.QueryRowContext(ctx, getOperationForClient, arg.ID, arg.ClientID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ApiVersion,
		&i.Broker,
		&i.ClientID,
		&i.IdempotencyKey,
		&i.Operation,
		&i.TargetJson,
		&i.ArgumentsJson,
		&i.Reason,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
		&i.ApprovalID,
		&i.PresentationJson,
		&i.ResultJson,
		&i.ErrorJson,
		&i.PlanDigest,
	)
	return i, err
}

const getOperationUsage = `-- name: GetOperationUsage :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN client_id = ?1 AND state NOT IN ('succeeded','failed','denied','expired','canceled') THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_active,
    CAST(COALESCE(SUM(CASE WHEN client_id = ?1 AND state = 'pending' THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_pending,
    CAST(COALESCE(SUM(CASE WHEN state NOT IN ('succeeded','failed','denied','expired','canceled') THEN 1 ELSE 0 END), 0) AS INTEGER) AS global_active,
    CAST(COALESCE(SUM(CASE WHEN state = 'executing' THEN 1 ELSE 0 END), 0) AS INTEGER) AS global_executing
FROM operations
`

type GetOperationUsageRow struct {
	ClientActive    int64
	ClientPending   int64
	GlobalActive    int64
	GlobalExecuting int64
}

// GetOperationUsage
//
//	SELECT
//	    CAST(COALESCE(SUM(CASE WHEN client_id = ?1 AND state NOT IN ('succeeded','failed','denied','expired','canceled') THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_active,
//	    CAST(COALESCE(SUM(CASE WHEN client_id = ?1 AND state = 'pending' THEN 1 ELSE 0 END), 0) AS INTEGER) AS client_pending,
//	    CAST(COALESCE(SUM(CASE WHEN state NOT IN ('succeeded','failed','denied','expired','canceled') THEN 1 ELSE 0 END), 0) AS INTEGER) AS global_active,
//	    CAST(COALESCE(SUM(CASE WHEN state = 'executing' THEN 1 ELSE 0 END), 0) AS INTEGER) AS global_executing
//	FROM operations
func (q *Queries) GetOperationUsage(ctx context.Context, clientID string) (GetOperationUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getOperationUsage, clientID)
	var i GetOperationUsageRow
	err := row.Scan(
		&i.ClientActive,
		&i.ClientPending,
		&i.GlobalActive,
		&i.GlobalExecuting,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT digest, schema_name, canonical, created_at
FROM plans
WHERE digest = ?
`

// GetPlan
//
//	SELECT digest, schema_name, canonical, created_at
//	FROM plans
//	WHERE digest = ?
func (q *Queries) GetPlan(ctx context.Context, digest string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, digest)
	var i Plan
	err := row.Scan(
		&i.Digest,
		&i.SchemaName,
		&i.Canonical,
		&i.CreatedAt,
	)
	return i, err
}

const health = `-- name: Health :one
SELECT 1
`

// Health
//
//	SELECT 1
func (q *Queries) Health(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, health)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertDecisionRecord = `-- name: InsertDecisionRecord :exec
INSERT INTO decision_records (
    scope, request_id, action, idempotency_key, command_hash,
    result_json, previous_json, event_cursor, committed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDecisionRecordParams struct {
	Scope          string
	RequestID      string
	Action         string
	IdempotencyKey string
	CommandHash    string
	ResultJson     string
	PreviousJson   string
	EventCursor    string
	CommittedAt    string
}

// InsertDecisionRecord
//
//	INSERT INTO decision_records (
//	    scope, request_id, action, idempotency_key, command_hash,
//	    result_json, previous_json, event_cursor, committed_at
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) InsertDecisionRecord(ctx context.Context, arg InsertDecisionRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertDecisionRecord,
		arg.Scope,
		arg.RequestID,
		arg.Action,
		arg.IdempotencyKey,
		arg.CommandHash,
		arg.ResultJson,
		arg.PreviousJson,
		arg.EventCursor,
		arg.CommittedAt,
	)
	return err
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO grants (
    id, decision_token_verifier, client, client_request_id, operation,
    target_json, attrs_json, metadata_json, plan_digest, reason, status,
    revision, created_at, pending_expires_at, expires_at, duration_ns,
    requested_duration_ns, pending_timeout_ns, decided_at, decided_by,
    decided_on_behalf_of, used_at, used_count, use_revision,
    reserved_count, reserved_at, reservation_retained, reservation_revision,
	max_uses, requested_max_uses, requested_max_uses_defaulted, expired_from, notification_json,
    notification_status, notification_claimed_at, notification_claim_until,
    notification_delivery_unresolved
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertGrantParams struct {
	ID                             string
	DecisionTokenVerifier          string
	Client                         string
	ClientRequestID                string
	Operation                      string
	TargetJson                     string
	AttrsJson                      string
	MetadataJson                   string
	PlanDigest                     sql.NullString
	Reason                         string
	Status                         string
	Revision                       int64
	CreatedAt                      string
	PendingExpiresAt               string
	ExpiresAt                      sql.NullString
	DurationNs                     int64
	RequestedDurationNs            int64
	PendingTimeoutNs               int64
	DecidedAt                      sql.NullString
	DecidedBy                      string
	DecidedOnBehalfOf              string
	UsedAt                         sql.NullString
	UsedCount                      int64
	UseRevision                    int64
	ReservedCount                  int64
	ReservedAt                     sql.NullString
	ReservationRetained            int64
	ReservationRevision            int64
	MaxUses                        sql.NullInt64
	RequestedMaxUses               sql.NullInt64
	RequestedMaxUsesDefaulted      int64
	ExpiredFrom                    sql.NullString
	NotificationJson               sql.NullString
	NotificationStatus             string
	NotificationClaimedAt          sql.NullString
	NotificationClaimUntil         sql.NullString
	NotificationDeliveryUnresolved int64
}

// InsertGrant
//
//	INSERT INTO grants (
//	    id, decision_token_verifier, client, client_request_id, operation,
//	    target_json, attrs_json, metadata_json, plan_digest, reason, status,
//	    revision, created_at, pending_expires_at, expires_at, duration_ns,
//	    requested_duration_ns, pending_timeout_ns, decided_at, decided_by,
//	    decided_on_behalf_of, used_at, used_count, use_revision,
//	    reserved_count, reserved_at, reservation_retained, reservation_revision,
//		max_uses, requested_max_uses, requested_max_uses_defaulted, expired_from, notification_json,
//	    notification_status, notification_claimed_at, notification_claim_until,
//	    notification_delivery_unresolved
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
//		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
//	)
func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.ExecContext(ctx, insertGrant,
		arg.ID,
		arg.DecisionTokenVerifier,
		arg.Client,
		arg.ClientRequestID,
		arg.Operation,
		arg.TargetJson,
		arg.AttrsJson,
		arg.MetadataJson,
		arg.PlanDigest,
		arg.Reason,
		arg.Status,
		arg.Revision,
		arg.CreatedAt,
		arg.PendingExpiresAt,
		arg.ExpiresAt,
		arg.DurationNs,
		arg.RequestedDurationNs,
		arg.PendingTimeoutNs,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedOnBehalfOf,
		arg.UsedAt,
		arg.UsedCount,
		arg.UseRevision,
		arg.ReservedCount,
		arg.ReservedAt,
		arg.ReservationRetained,
		arg.ReservationRevision,
		arg.MaxUses,
		arg.RequestedMaxUses,
		arg.RequestedMaxUsesDefaulted,
		arg.ExpiredFrom,
		arg.NotificationJson,
		arg.NotificationStatus,
		arg.NotificationClaimedAt,
		arg.NotificationClaimUntil,
		arg.NotificationDeliveryUnresolved,
	)
	return err
}

const insertGrantLifecycleEvent = `-- name: InsertGrantLifecycleEvent :exec
INSERT INTO lifecycle_events (
    sequence, cursor, subject_kind, subject_id, kind, revision, occurred_at, payload_json
) VALUES (?, ?, 'grant', ?, ?, ?, ?, ?)
`

type InsertGrantLifecycleEventParams struct {
	Sequence    int64
	Cursor      string
	SubjectID   string
	Kind        string
	Revision    int64
	OccurredAt  string
	PayloadJson string
}

// InsertGrantLifecycleEvent
//
//	INSERT INTO lifecycle_events (
//	    sequence, cursor, subject_kind, subject_id, kind, revision, occurred_at, payload_json
//	) VALUES (?, ?, 'grant', ?, ?, ?, ?, ?)
func (q *Queries) InsertGrantLifecycleEvent(ctx context.Context, arg InsertGrantLifecycleEventParams) error {
	_, err := q.db.ExecContext(ctx, insertGrantLifecycleEvent,
		arg.Sequence,
		arg.Cursor,
		arg.SubjectID,
		arg.Kind,
		arg.Revision,
		arg.OccurredAt,
		arg.PayloadJson,
	)
	return err
}

const insertNotificationOutbox = `-- name: InsertNotificationOutbox :exec
INSERT INTO notification_outbox (
    grant_id, kind, payload_json, idempotency_key, status, attempts,
    available_at, claimed_until, delivered_at, last_error_code, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNotificationOutboxParams struct {
	GrantID        string
	Kind           string
	PayloadJson    string
	IdempotencyKey string
	Status         string
	Attempts       int64
	AvailableAt    string
	ClaimedUntil   sql.NullString
	DeliveredAt    sql.NullString
	LastErrorCode  string
	CreatedAt      string
	UpdatedAt      string
}

// InsertNotificationOutbox
//
//	INSERT INTO notification_outbox (
//	    grant_id, kind, payload_json, idempotency_key, status, attempts,
//	    available_at, claimed_until, delivered_at, last_error_code, created_at, updated_at
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) InsertNotificationOutbox(ctx context.Context, arg InsertNotificationOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertNotificationOutbox,
		arg.GrantID,
		arg.Kind,
		arg.PayloadJson,
		arg.IdempotencyKey,
		arg.Status,
		arg.Attempts,
		arg.AvailableAt,
		arg.ClaimedUntil,
		arg.DeliveredAt,
		arg.LastErrorCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO operations (
    id, api_version, broker, client_id, idempotency_key, operation,
    target_json, arguments_json, reason, state, revision, created_at, updated_at,
    terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertOperationParams struct {
	ID               string
	ApiVersion       string
	Broker           string
	ClientID         string
	IdempotencyKey   string
	Operation        string
	TargetJson       string
	ArgumentsJson    string
	Reason           string
	State            string
	Revision         int64
	CreatedAt        string
	UpdatedAt        string
	TerminalAt       sql.NullString
	ApprovalID       string
	PresentationJson string
	ResultJson       sql.NullString
	ErrorJson        sql.NullString
	PlanDigest       sql.NullString
}

// InsertOperation
//
//	INSERT INTO operations (
//	    id, api_version, broker, client_id, idempotency_key, operation,
//	    target_json, arguments_json, reason, state, revision, created_at, updated_at,
//	    terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest
//	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertOperation,
		arg.ID,
		arg.ApiVersion,
		arg.Broker,
		arg.ClientID,
		arg.IdempotencyKey,
		arg.Operation,
		arg.TargetJson,
		arg.ArgumentsJson,
		arg.Reason,
		arg.State,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TerminalAt,
		arg.ApprovalID,
		arg.PresentationJson,
		arg.ResultJson,
		arg.ErrorJson,
		arg.PlanDigest,
	)
	return err
}

const listDecisionRecords = `-- name: ListDecisionRecords :many
SELECT scope, request_id, "action", idempotency_key, command_hash, result_json, previous_json, event_cursor, committed_at FROM decision_records ORDER BY committed_at, scope
`

// ListDecisionRecords
//
//	SELECT scope, request_id, "action", idempotency_key, command_hash, result_json, previous_json, event_cursor, committed_at FROM decision_records ORDER BY committed_at, scope
func (q *Queries) ListDecisionRecords(ctx context.Context) ([]DecisionRecord, error) {
	rows, err := q.db.QueryContext(ctx, listDecisionRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DecisionRecord{}
	for rows.Next() {
		var i DecisionRecord
		if err := rows.Scan(
			&i.Scope,
			&i.RequestID,
			&i.Action,
			&i.IdempotencyKey,
			&i.CommandHash,
			&i.ResultJson,
			&i.PreviousJson,
			&i.EventCursor,
			&i.CommittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantLifecycleEvents = `-- name: ListGrantLifecycleEvents :many
SELECT sequence, cursor, subject_kind, subject_id, kind, revision, occurred_at, payload_json FROM lifecycle_events
WHERE subject_kind = 'grant'
ORDER BY sequence
`

// ListGrantLifecycleEvents
//
//	SELECT sequence, cursor, subject_kind, subject_id, kind, revision, occurred_at, payload_json FROM lifecycle_events
//	WHERE subject_kind = 'grant'
//	ORDER BY sequence
func (q *Queries) ListGrantLifecycleEvents(ctx context.Context) ([]LifecycleEvent, error) {
	rows, err := q.db.QueryContext(ctx, listGrantLifecycleEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LifecycleEvent{}
	for rows.Next() {
		var i LifecycleEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.Cursor,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Kind,
			&i.Revision,
			&i.OccurredAt,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrants = `-- name: ListGrants :many
SELECT id, decision_token_verifier, client, client_request_id, operation, target_json, attrs_json, metadata_json, plan_digest, reason, status, revision, created_at, pending_expires_at, expires_at, duration_ns, requested_duration_ns, pending_timeout_ns, decided_at, decided_by, decided_on_behalf_of, used_at, used_count, use_revision, reserved_count, reserved_at, reservation_retained, reservation_revision, max_uses, requested_max_uses, requested_max_uses_defaulted, expired_from, notification_json, notification_status, notification_claimed_at, notification_claim_until, notification_delivery_unresolved FROM grants ORDER BY created_at, id
`

// ListGrants
//
//	SELECT id, decision_token_verifier, client, client_request_id, operation, target_json, attrs_json, metadata_json, plan_digest, reason, status, revision, created_at, pending_expires_at, expires_at, duration_ns, requested_duration_ns, pending_timeout_ns, decided_at, decided_by, decided_on_behalf_of, used_at, used_count, use_revision, reserved_count, reserved_at, reservation_retained, reservation_revision, max_uses, requested_max_uses, requested_max_uses_defaulted, expired_from, notification_json, notification_status, notification_claimed_at, notification_claim_until, notification_delivery_unresolved FROM grants ORDER BY created_at, id
func (q *Queries) ListGrants(ctx context.Context) ([]Grant, error) {
	rows, err := q.db.QueryContext(ctx, listGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Grant{}
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.DecisionTokenVerifier,
			&i.Client,
			&i.ClientRequestID,
			&i.Operation,
			&i.TargetJson,
			&i.AttrsJson,
			&i.MetadataJson,
			&i.PlanDigest,
			&i.Reason,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
			&i.PendingExpiresAt,
			&i.ExpiresAt,
			&i.DurationNs,
			&i.RequestedDurationNs,
			&i.PendingTimeoutNs,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedOnBehalfOf,
			&i.UsedAt,
			&i.UsedCount,
			&i.UseRevision,
			&i.ReservedCount,
			&i.ReservedAt,
			&i.ReservationRetained,
			&i.ReservationRevision,
			&i.MaxUses,
			&i.RequestedMaxUses,
			&i.RequestedMaxUsesDefaulted,
			&i.ExpiredFrom,
			&i.NotificationJson,
			&i.NotificationStatus,
			&i.NotificationClaimedAt,
			&i.NotificationClaimUntil,
			&i.NotificationDeliveryUnresolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationOutbox = `-- name: ListNotificationOutbox :many
SELECT id, grant_id, kind, payload_json, idempotency_key, status, attempts, available_at, claimed_until, delivered_at, last_error_code, created_at, updated_at FROM notification_outbox ORDER BY id
`

// ListNotificationOutbox
//
//	SELECT id, grant_id, kind, payload_json, idempotency_key, status, attempts, available_at, claimed_until, delivered_at, last_error_code, created_at, updated_at FROM notification_outbox ORDER BY id
func (q *Queries) ListNotificationOutbox(ctx context.Context) ([]NotificationOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.GrantID,
			&i.Kind,
			&i.PayloadJson,
			&i.IdempotencyKey,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.ClaimedUntil,
			&i.DeliveredAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsForClient = `-- name: ListOperationsForClient :many
SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations
WHERE client_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR idempotency_key = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) = '' OR state = CAST(?3 AS TEXT))
  AND (
    CAST(?4 AS TEXT) = ''
    OR created_at < CAST(?4 AS TEXT)
    OR (created_at = CAST(?4 AS TEXT) AND id < ?5)
  )
ORDER BY created_at DESC, id DESC
LIMIT ?6
`

type ListOperationsForClientParams struct {
	ClientID        string
	IdempotencyKey  string
	State           string
	CursorCreatedAt string
	CursorID        string
	PageSize        int64
}

// ListOperationsForClient
//
//	SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations
//	WHERE client_id = ?1
//	  AND (CAST(?2 AS TEXT) = '' OR idempotency_key = CAST(?2 AS TEXT))
//	  AND (CAST(?3 AS TEXT) = '' OR state = CAST(?3 AS TEXT))
//	  AND (
//	    CAST(?4 AS TEXT) = ''
//	    OR created_at < CAST(?4 AS TEXT)
//	    OR (created_at = CAST(?4 AS TEXT) AND id < ?5)
//	  )
//	ORDER BY created_at DESC, id DESC
//	LIMIT ?6
func (q *Queries) ListOperationsForClient(ctx context.Context, arg ListOperationsForClientParams) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, listOperationsForClient,
		arg.ClientID,
		arg.IdempotencyKey,
		arg.State,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.Broker,
			&i.ClientID,
			&i.IdempotencyKey,
			&i.Operation,
			&i.TargetJson,
			&i.ArgumentsJson,
			&i.Reason,
			&i.State,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
			&i.ApprovalID,
			&i.PresentationJson,
			&i.ResultJson,
			&i.ErrorJson,
			&i.PlanDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedOperations = `-- name: ListUnfinishedOperations :many
SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations
WHERE state NOT IN ('succeeded','failed','denied','expired','canceled')
ORDER BY created_at, id
`

// ListUnfinishedOperations
//
//	SELECT id, api_version, broker, client_id, idempotency_key, operation, target_json, arguments_json, reason, state, revision, created_at, updated_at, terminal_at, approval_id, presentation_json, result_json, error_json, plan_digest FROM operations
//	WHERE state NOT IN ('succeeded','failed','denied','expired','canceled')
//	ORDER BY created_at, id
func (q *Queries) ListUnfinishedOperations(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ApiVersion,
			&i.Broker,
			&i.ClientID,
			&i.IdempotencyKey,
			&i.Operation,
			&i.TargetJson,
			&i.ArgumentsJson,
			&i.Reason,
			&i.State,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
			&i.ApprovalID,
			&i.PresentationJson,
			&i.ResultJson,
			&i.ErrorJson,
			&i.PlanDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putPlan = `-- name: PutPlan :exec
INSERT INTO plans (digest, schema_name, canonical, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(digest) DO NOTHING
`

type PutPlanParams struct {
	Digest     string
	SchemaName string
	Canonical  []byte
	CreatedAt  string
}

// PutPlan
//
//	INSERT INTO plans (digest, schema_name, canonical, created_at)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT(digest) DO NOTHING
func (q *Queries) PutPlan(ctx context.Context, arg PutPlanParams) error {
	_, err := q.db.ExecContext(ctx, putPlan,
		arg.Digest,
		arg.SchemaName,
		arg.Canonical,
		arg.CreatedAt,
	)
	return err
}

const updateGrant = `-- name: UpdateGrant :execrows
UPDATE grants SET
    decision_token_verifier = ?, client = ?, client_request_id = ?, operation = ?,
    target_json = ?, attrs_json = ?, metadata_json = ?, plan_digest = ?, reason = ?,
    status = ?, revision = ?, created_at = ?, pending_expires_at = ?, expires_at = ?,
    duration_ns = ?, requested_duration_ns = ?, pending_timeout_ns = ?, decided_at = ?,
    decided_by = ?, decided_on_behalf_of = ?, used_at = ?,
    used_count = ?, use_revision = ?, reserved_count = ?, reserved_at = ?,
    reservation_retained = ?, reservation_revision = ?, max_uses = ?,
	requested_max_uses = ?, requested_max_uses_defaulted = ?, expired_from = ?, notification_json = ?,
    notification_status = ?, notification_claimed_at = ?, notification_claim_until = ?,
    notification_delivery_unresolved = ?
WHERE id = ? AND revision = ?
`

type UpdateGrantParams struct {
	DecisionTokenVerifier          string
	Client                         string
	ClientRequestID                string
	Operation                      string
	TargetJson                     string
	AttrsJson                      string
	MetadataJson                   string
	PlanDigest                     sql.NullString
	Reason                         string
	Status                         string
	Revision                       int64
	CreatedAt                      string
	PendingExpiresAt               string
	ExpiresAt                      sql.NullString
	DurationNs                     int64
	RequestedDurationNs            int64
	PendingTimeoutNs               int64
	DecidedAt                      sql.NullString
	DecidedBy                      string
	DecidedOnBehalfOf              string
	UsedAt                         sql.NullString
	UsedCount                      int64
	UseRevision                    int64
	ReservedCount                  int64
	ReservedAt                     sql.NullString
	ReservationRetained            int64
	ReservationRevision            int64
	MaxUses                        sql.NullInt64
	RequestedMaxUses               sql.NullInt64
	RequestedMaxUsesDefaulted      int64
	ExpiredFrom                    sql.NullString
	NotificationJson               sql.NullString
	NotificationStatus             string
	NotificationClaimedAt          sql.NullString
	NotificationClaimUntil         sql.NullString
	NotificationDeliveryUnresolved int64
	ID                             string
	Revision_2                     int64
}

// UpdateGrant
//
//	UPDATE grants SET
//	    decision_token_verifier = ?, client = ?, client_request_id = ?, operation = ?,
//	    target_json = ?, attrs_json = ?, metadata_json = ?, plan_digest = ?, reason = ?,
//	    status = ?, revision = ?, created_at = ?, pending_expires_at = ?, expires_at = ?,
//	    duration_ns = ?, requested_duration_ns = ?, pending_timeout_ns = ?, decided_at = ?,
//	    decided_by = ?, decided_on_behalf_of = ?, used_at = ?,
//	    used_count = ?, use_revision = ?, reserved_count = ?, reserved_at = ?,
//	    reservation_retained = ?, reservation_revision = ?, max_uses = ?,
//		requested_max_uses = ?, requested_max_uses_defaulted = ?, expired_from = ?, notification_json = ?,
//	    notification_status = ?, notification_claimed_at = ?, notification_claim_until = ?,
//	    notification_delivery_unresolved = ?
//	WHERE id = ? AND revision = ?
func (q *Queries) UpdateGrant(ctx context.Context, arg UpdateGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGrant,
		arg.DecisionTokenVerifier,
		arg.Client,
		arg.ClientRequestID,
		arg.Operation,
		arg.TargetJson,
		arg.AttrsJson,
		arg.MetadataJson,
		arg.PlanDigest,
		arg.Reason,
		arg.Status,
		arg.Revision,
		arg.CreatedAt,
		arg.PendingExpiresAt,
		arg.ExpiresAt,
		arg.DurationNs,
		arg.RequestedDurationNs,
		arg.PendingTimeoutNs,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.DecidedOnBehalfOf,
		arg.UsedAt,
		arg.UsedCount,
		arg.UseRevision,
		arg.ReservedCount,
		arg.ReservedAt,
		arg.ReservationRetained,
		arg.ReservationRevision,
		arg.MaxUses,
		arg.RequestedMaxUses,
		arg.RequestedMaxUsesDefaulted,
		arg.ExpiredFrom,
		arg.NotificationJson,
		arg.NotificationStatus,
		arg.NotificationClaimedAt,
		arg.NotificationClaimUntil,
		arg.NotificationDeliveryUnresolved,
		arg.ID,
		arg.Revision_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNotificationOutbox = `-- name: UpdateNotificationOutbox :execrows
UPDATE notification_outbox SET
    kind = ?, payload_json = ?, idempotency_key = ?, status = ?, attempts = ?,
    available_at = ?, claimed_until = ?, delivered_at = ?, last_error_code = ?, updated_at = ?
WHERE id = ? AND grant_id = ? AND status = ? AND attempts = ?
`

type UpdateNotificationOutboxParams struct {
	Kind           string
	PayloadJson    string
	IdempotencyKey string
	Status         string
	Attempts       int64
	AvailableAt    string
	ClaimedUntil   sql.NullString
	DeliveredAt    sql.NullString
	LastErrorCode  string
	UpdatedAt      string
	ID             int64
	GrantID        string
	Status_2       string
	Attempts_2     int64
}

// UpdateNotificationOutbox
//
//	UPDATE notification_outbox SET
//	    kind = ?, payload_json = ?, idempotency_key = ?, status = ?, attempts = ?,
//	    available_at = ?, claimed_until = ?, delivered_at = ?, last_error_code = ?, updated_at = ?
//	WHERE id = ? AND grant_id = ? AND status = ? AND attempts = ?
func (q *Queries) UpdateNotificationOutbox(ctx context.Context, arg UpdateNotificationOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNotificationOutbox,
		arg.Kind,
		arg.PayloadJson,
		arg.IdempotencyKey,
		arg.Status,
		arg.Attempts,
		arg.AvailableAt,
		arg.ClaimedUntil,
		arg.DeliveredAt,
		arg.LastErrorCode,
		arg.UpdatedAt,
		arg.ID,
		arg.GrantID,
		arg.Status_2,
		arg.Attempts_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOperation = `-- name: UpdateOperation :execrows
UPDATE operations SET
    state = ?, revision = ?, updated_at = ?, terminal_at = ?, approval_id = ?,
    result_json = ?, error_json = ?, plan_digest = ?
WHERE id = ? AND revision = ?
`

type UpdateOperationParams struct {
	State      string
	Revision   int64
	UpdatedAt  string
	TerminalAt sql.NullString
	ApprovalID string
	ResultJson sql.NullString
	ErrorJson  sql.NullString
	PlanDigest sql.NullString
	ID         string
	Revision_2 int64
}

// UpdateOperation
//
//	UPDATE operations SET
//	    state = ?, revision = ?, updated_at = ?, terminal_at = ?, approval_id = ?,
//	    result_json = ?, error_json = ?, plan_digest = ?
//	WHERE id = ? AND revision = ?
func (q *Queries) UpdateOperation(ctx context.Context, arg UpdateOperationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOperation,
		arg.State,
		arg.Revision,
		arg.UpdatedAt,
		arg.TerminalAt,
		arg.ApprovalID,
		arg.ResultJson,
		arg.ErrorJson,
		arg.PlanDigest,
		arg.ID,
		arg.Revision_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
