// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsql

import (
	"context"
)

const countPlans = `-- name: CountPlans :one
SELECT count(*) FROM plans
`

// CountPlans
//
//	SELECT count(*) FROM plans
func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlan = `-- name: GetPlan :one
SELECT digest, schema_name, canonical, created_at
FROM plans
WHERE digest = ?
`

// GetPlan
//
//	SELECT digest, schema_name, canonical, created_at
//	FROM plans
//	WHERE digest = ?
func (q *Queries) GetPlan(ctx context.Context, digest string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, digest)
	var i Plan
	err := row.Scan(
		&i.Digest,
		&i.SchemaName,
		&i.Canonical,
		&i.CreatedAt,
	)
	return i, err
}

const health = `-- name: Health :one
SELECT 1
`

// Health
//
//	SELECT 1
func (q *Queries) Health(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, health)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const putPlan = `-- name: PutPlan :exec
INSERT INTO plans (digest, schema_name, canonical, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(digest) DO NOTHING
`

type PutPlanParams struct {
	Digest     string
	SchemaName string
	Canonical  []byte
	CreatedAt  string
}

// PutPlan
//
//	INSERT INTO plans (digest, schema_name, canonical, created_at)
//	VALUES (?, ?, ?, ?)
//	ON CONFLICT(digest) DO NOTHING
func (q *Queries) PutPlan(ctx context.Context, arg PutPlanParams) error {
	_, err := q.db.ExecContext(ctx, putPlan,
		arg.Digest,
		arg.SchemaName,
		arg.Canonical,
		arg.CreatedAt,
	)
	return err
}
