package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPolicyRenderCheckAndDoctorEndToEnd(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "policy-profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "policy-manifest.json")
	args := []string{
		"policy", "render", "--client", "agent", "--deny-operation", "repo.delete",
		"--profile-out", profilePath, "--output", policyPath, "--manifest-out", manifestPath,
	}
	var stdout bytes.Buffer
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, args); err != nil {
		t.Fatalf("policy render error = %v", err)
	}
	if !strings.Contains(stdout.String(), "258 operation(s)") {
		t.Fatalf("policy render output = %q", stdout.String())
	}
	for _, path := range []string{profilePath, policyPath, manifestPath} {
		if info, err := os.Stat(path); err != nil || info.Mode().Perm() != 0o644 {
			t.Fatalf("rendered artifact %s: info=%v err=%v", path, info, err)
		}
	}
	stdout.Reset()
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{"policy", "check", "--file", policyPath}); err != nil {
		t.Fatalf("policy check error = %v", err)
	}
	stdout.Reset()
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{"doctor", "policy", "--profile", profilePath, "--scope", policyPath, "--manifest", manifestPath}); err != nil {
		t.Fatalf("doctor policy error = %v", err)
	}
	if !strings.Contains(stdout.String(), "Policy status: current") {
		t.Fatalf("doctor output = %q", stdout.String())
	}
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, args); err == nil || !strings.Contains(err.Error(), "--replace") {
		t.Fatalf("second render error = %v", err)
	}
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, append(args, "--replace")); err != nil {
		t.Fatalf("replacement render error = %v", err)
	}
}

func TestDoctorPolicyReportsModifiedPolicyAsJSON(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "manifest.json")
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", profilePath, "--output", policyPath, "--manifest-out", manifestPath,
	}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(policyPath)
	if err != nil {
		t.Fatal(err)
	}
	data = bytes.Replace(data, []byte("Generated by"), []byte("Rendered by"), 1)
	if err := os.WriteFile(policyPath, data, 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout bytes.Buffer
	err = runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{
		"doctor", "policy", "--profile", profilePath, "--scope", policyPath, "--manifest", manifestPath, "--json",
	})
	var exitErr exitError
	if err == nil || !strings.Contains(stdout.String(), `"status": "modified"`) || !strings.Contains(stdout.String(), "policy digest") || !errors.As(err, &exitErr) || exitErr.code != 1 {
		t.Fatalf("doctor modified result: output=%q error=%v", stdout.String(), err)
	}
}

func TestDoctorPolicyReportsMissingArtifactAsInvalidJSON(t *testing.T) {
	dir := t.TempDir()
	var stdout bytes.Buffer
	err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{
		"doctor", "policy", "--profile", filepath.Join(dir, "missing-profile.json"),
		"--scope", filepath.Join(dir, "missing-scope.json"),
		"--manifest", filepath.Join(dir, "missing-manifest.json"), "--json",
	})
	var exitErr exitError
	if err == nil || !errors.As(err, &exitErr) || exitErr.code != 2 ||
		!strings.Contains(stdout.String(), `"status": "invalid"`) || !strings.Contains(stdout.String(), "missing-profile.json") {
		t.Fatalf("doctor missing result: output=%q error=%v", stdout.String(), err)
	}
}

func TestPolicyRenderRejectsDuplicateOutputPaths(t *testing.T) {
	path := filepath.Join(t.TempDir(), "artifact.json")
	err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", path, "--output", path, "--manifest-out", path + ".manifest",
	})
	if err == nil || !strings.Contains(err.Error(), "must be distinct") {
		t.Fatalf("duplicate output error = %v", err)
	}
}

func TestPolicyRenderRejectsEquivalentAndSymlinkedOutputPaths(t *testing.T) {
	dir := t.TempDir()
	realDir := filepath.Join(dir, "real")
	if err := os.Mkdir(realDir, 0o700); err != nil {
		t.Fatal(err)
	}
	aliasDir := filepath.Join(dir, "alias")
	if err := os.Symlink(realDir, aliasDir); err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name    string
		policy  string
		profile string
	}{
		{name: "cleaned", policy: realDir + "/scope.json", profile: realDir + "/./scope.json"},
		{name: "symlinked parent", policy: filepath.Join(realDir, "scope.json"), profile: filepath.Join(aliasDir, "scope.json")},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
				"policy", "render", "--profile-out", test.profile, "--output", test.policy,
				"--manifest-out", filepath.Join(dir, test.name+"-manifest.json"),
			})
			if err == nil || !strings.Contains(err.Error(), "must be distinct") {
				t.Fatalf("aliased output error = %v", err)
			}
		})
	}
}

func TestPolicyRenderStagesEveryArtifactBeforeCreatingOutputs(t *testing.T) {
	dir := t.TempDir()
	blockedParent := filepath.Join(dir, "not-a-directory")
	if err := os.WriteFile(blockedParent, []byte("block"), 0o600); err != nil {
		t.Fatal(err)
	}
	profilePath := filepath.Join(dir, "profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", profilePath, "--output", policyPath,
		"--manifest-out", filepath.Join(blockedParent, "manifest.json"),
	})
	if err == nil {
		t.Fatal("render with an unstaged manifest unexpectedly succeeded")
	}
	for _, path := range []string{profilePath, policyPath} {
		if _, statErr := os.Stat(path); !errors.Is(statErr, os.ErrNotExist) {
			t.Fatalf("failed render created %s: %v", path, statErr)
		}
	}
}

func TestPolicyRenderNoReplacePreservesAllExistingArtifacts(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "manifest.json")
	if err := os.WriteFile(manifestPath, []byte("existing"), 0o600); err != nil {
		t.Fatal(err)
	}
	err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", profilePath, "--output", policyPath,
		"--manifest-out", manifestPath,
	})
	if err == nil || !strings.Contains(err.Error(), "--replace") {
		t.Fatalf("no-replace render error = %v", err)
	}
	for _, path := range []string{profilePath, policyPath} {
		if _, statErr := os.Stat(path); !errors.Is(statErr, os.ErrNotExist) {
			t.Fatalf("rolled-back render retained %s: %v", path, statErr)
		}
	}
	data, readErr := os.ReadFile(manifestPath)
	if readErr != nil || string(data) != "existing" {
		t.Fatalf("existing artifact = %q, error = %v", data, readErr)
	}
}

func TestPolicyRenderReplaceRollsBackBeforeCommitFailure(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "manifest.json")
	for _, path := range []string{profilePath, policyPath} {
		if err := os.WriteFile(path, []byte("existing"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.Mkdir(manifestPath, 0o700); err != nil {
		t.Fatal(err)
	}
	err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--replace", "--profile-out", profilePath,
		"--output", policyPath, "--manifest-out", manifestPath,
	})
	if err == nil || !strings.Contains(err.Error(), "directory") {
		t.Fatalf("replace render error = %v", err)
	}
	for _, path := range []string{profilePath, policyPath} {
		data, readErr := os.ReadFile(path)
		if readErr != nil || string(data) != "existing" {
			t.Fatalf("rolled-back artifact %s = %q, error = %v", path, data, readErr)
		}
	}
	if info, statErr := os.Stat(manifestPath); statErr != nil || !info.IsDir() {
		t.Fatalf("manifest directory changed: info=%v error=%v", info, statErr)
	}
}

func TestBackupPolicyArtifactKeepsOriginalPathPresent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "scope.json")
	if err := os.WriteFile(path, []byte("existing"), 0o600); err != nil {
		t.Fatal(err)
	}
	artifact, err := stagePolicyArtifact(policyArtifactOutput{path: path, data: []byte("replacement")})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { cleanupPolicyArtifactTransaction([]*stagedPolicyArtifact{artifact}) })
	if err := backupPolicyArtifact(artifact); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil || string(data) != "existing" {
		t.Fatalf("original path after backup = %q, error = %v", data, err)
	}
	if err := rollbackPolicyArtifact(artifact); err != nil {
		t.Fatal(err)
	}
	if artifact.backup != "" {
		t.Fatalf("backup path was not cleared: %s", artifact.backup)
	}
}
