package main

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPolicyRenderCheckAndDoctorEndToEnd(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "policy-profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "policy-manifest.json")
	args := []string{
		"policy", "render", "--client", "agent", "--deny-operation", "repo.delete",
		"--profile-out", profilePath, "--output", policyPath, "--manifest-out", manifestPath,
	}
	var stdout bytes.Buffer
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, args); err != nil {
		t.Fatalf("policy render error = %v", err)
	}
	if !strings.Contains(stdout.String(), "258 operation(s)") {
		t.Fatalf("policy render output = %q", stdout.String())
	}
	for _, path := range []string{profilePath, policyPath, manifestPath} {
		if info, err := os.Stat(path); err != nil || info.Mode().Perm() != 0o644 {
			t.Fatalf("rendered artifact %s: info=%v err=%v", path, info, err)
		}
	}
	stdout.Reset()
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{"policy", "check", "--file", policyPath}); err != nil {
		t.Fatalf("policy check error = %v", err)
	}
	stdout.Reset()
	if err := runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{"doctor", "policy", "--profile", profilePath, "--scope", policyPath, "--manifest", manifestPath}); err != nil {
		t.Fatalf("doctor policy error = %v", err)
	}
	if !strings.Contains(stdout.String(), "Policy status: current") {
		t.Fatalf("doctor output = %q", stdout.String())
	}
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, args); err == nil || !strings.Contains(err.Error(), "--replace") {
		t.Fatalf("second render error = %v", err)
	}
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, append(args, "--replace")); err != nil {
		t.Fatalf("replacement render error = %v", err)
	}
}

func TestDoctorPolicyReportsModifiedPolicyAsJSON(t *testing.T) {
	dir := t.TempDir()
	profilePath := filepath.Join(dir, "profile.json")
	policyPath := filepath.Join(dir, "scope.json")
	manifestPath := filepath.Join(dir, "manifest.json")
	if err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", profilePath, "--output", policyPath, "--manifest-out", manifestPath,
	}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(policyPath)
	if err != nil {
		t.Fatal(err)
	}
	data = bytes.Replace(data, []byte("Generated by"), []byte("Rendered by"), 1)
	if err := os.WriteFile(policyPath, data, 0o644); err != nil {
		t.Fatal(err)
	}
	var stdout bytes.Buffer
	err = runWithArgs(context.Background(), nil, &stdout, ioDiscard{}, []string{
		"doctor", "policy", "--profile", profilePath, "--scope", policyPath, "--manifest", manifestPath, "--json",
	})
	var exitErr exitError
	if err == nil || !strings.Contains(stdout.String(), `"status": "modified"`) || !strings.Contains(stdout.String(), "policy digest") || !errors.As(err, &exitErr) || exitErr.code != 1 {
		t.Fatalf("doctor modified result: output=%q error=%v", stdout.String(), err)
	}
}

func TestPolicyRenderRejectsDuplicateOutputPaths(t *testing.T) {
	path := filepath.Join(t.TempDir(), "artifact.json")
	err := runWithArgs(context.Background(), nil, ioDiscard{}, ioDiscard{}, []string{
		"policy", "render", "--profile-out", path, "--output", path, "--manifest-out", path + ".manifest",
	})
	if err == nil || !strings.Contains(err.Error(), "must be distinct") {
		t.Fatalf("duplicate output error = %v", err)
	}
}
